[7주차 미션] 박예은 미션 제출합니다
greedy-team/self-paced-react-advanced pull request #1
Opened 2024-11-19 13:51 UTC by ye6194

추가예정

2024-11-21 13:00 UTC, gogo1414 reviewed
안녕하세요, 예은님!
그동안 초록 미션 하시느라 고생 많으셨습니다!!

앗.. 저도 문제를 진행할 때 어디서부터 진행할 지 조금 생각이 들긴 했는데, 예은님은 전자로 진행하셨군요..!

기존 App.jsx에서 step5로 새롭게 바꾸신 내용들은 잘 봤습니다!
스타일 컴포넌트를 적용하실 때 각 태그별로 별도로 적용하시는게 아니라 가장 큰 상위의 컴포넌트에서 진행하셨던데 해당 부분에 대한 질문은 코드리뷰에 달아놨어요!

> 저는 평소에도 styled-components를 썼었는데요. 리뷰어님은 평소에 스타일링을 적용할 때 무슨 라이브러리나 프레임워크를 사용하셨는지 궁금합니다.

사실 저는 `styled-components` 라이브러리를 처음 사용해보는거라 이런 저런 코드 보면서 저렇게도 적용이 가능하고 `props`도 달 수 있구나 하고 경험(?) 위주의 체험으로 진행했네요!

> styled-components를 사용하는 이유?
> 컴포넌트 단위 스타일링 가능
> props나 상태를 기반으로 조건부 스타일링 가능

컴포넌트 단위의 스타일링도 가능하지만 그 안에 더 세부적으로 스타일링이 가능한 점도 장점이 된다고 생각해요😊

> trade-off
> styled-components 라이브러리를 설치해야 함
> 런타임에 스타일을 생성하기 때문에 성능 이슈가 발생할 수

이러한 부분은 몰랐던 사실인데 덕분에 알아갑니다!!👍

그리디 미션도 고생하셨습니다!!

2024-11-21 13:00 UTC, gogo1414 commented on src/style/AddRestaurantModalStyle.js
스타일 컴포넌트를 적용하실 때 각 태그별로 별도로 적용하시는게 아니라 가장 큰 상위의 컴포넌트에서 한 번에 넣어서 진행하셨던데, 혹시 하나의 컴포넌트 내에도 여러개의 태그들이 존재하는데, 평소에 프로젝트 시 별도로 적용하시진 않았나요??

똑같은 CSS를 별도로 적용하는 구간이 생기게 되면 조금 불편하지 않을까 싶어서 여쭤봅니다🧐

2024-11-24 08:29 UTC, Indigochi1d requested changes
안녕하세요 예은님😃금요일 시험 준비하느라 바쁘시겠군요..화이팅입니다🚀  이 미션에선 `styled-components`로  styling하는 것을 목적에 두고 구현하는 것이 목적이었습니다. 제가 자료를 만들때는 뭔가 한턴 쉬어가는 느낌으로 만들었는데

> 
> 안녕하세요!
> 
> 드디어 리팩토링을 끝냈네요. 스타일드 컴포넌트를 처음 사용한 것도 아닌데 은근 힘들었어요..

.....ㅎ 고생하셨습니다. README에서 절차를 소개하지 않아 예은님이 한번 헤매셔서 더 힘들다고 느끼실 수도 있을 것  같네요. 문서를 더 develop해야겠습니다..😢  

아무튼 평소에 styled-components 를 써오셔서 그런지 자연스럽게 스타일링 된 컴포넌트를 작성해주신 것이 인상깊었어요. 또, style이라는 디렉토리를 만들어 스타일링 컴포넌트를 따로 관리하는 것이 좋은 포인트가 되었다고 생각합니다!. styled-components가 어떻게 작동하는지 저도 얕게만 파봐서 몰랐는데 [이 메시지](https://discord.com/channels/1277285790270885889/1277617980146192435/1309882190909149204)를 보고 확인해보는 시간을 가지면 좋을 것 같이요. 저는 그럼 README에 적혀있던 브라우저가 웹 페이지를 렌더링하는 구조와 과정에 대해서 적어보도록 할게요!
 



## 브라우저의 웹 페이지 렌더링
### DOM
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Simple Page</title>
  <style>body { background-color: blue; }</style>
</head>
<body>
  <header>
	  <h1 style="display:flex;">Hello, World!</h1>
  </header>
  <main>
	  <p>안녕하세요?</p>
  </main>
</body>
</html>
```
html은 웹페이지를 구성하는 뼈대라는 것을 아실거에요. 이 코드를 그대로 메모장에 넣어서 `.txt` 확장자로 열어보면…? 그냥 텍스트일 뿐입니다. 이 텍스트를 브라우저가 HTML로서 읽어내었을 때 DOM이라는 실체를 만들어내게 돼요. 이 과정을` parsing`이라고 합니다.

![image](https://github.com/user-attachments/assets/b8ef16e0-5c70-405f-9a15-39629c616501)

### CSSOM(**CSS** **O**bject **M**odel)
HTML로부터 DOM이 만들어지듯 CSS로부터는 CSSOM이 만들어지는데요. 위의 코드를 CSSOM Tree는 아래처럼 만듭니다.
```text
CSSStyleSheet (style.css)
  └── CSSRuleList
      ├── CSSRule (h1)
      │   └── CSSStyleDeclaration
      │       └── (whatever you styled) props: value
      └── CSSRule (section)
          └── CSSStyleDeclaration
              ├── (whatever you styled) props: value
              └── (whatever you styled) props: value

CSSStyleSheet (internal styles)
  └── CSSRuleList
      └── CSSRule (body)
          └── CSSStyleDeclaration
              └── background-color: blue
              
CSSStyleSheet (inline styles)
  └── CSSRuleList
      └── CSSRule (h1)
          └── CSSStyleDeclaration
              └── style=display:flex
```
실제로 `document.styleSheets` 를 브라우저에서 동작시키면 css파일과 내부스타일로 작성된 CSSOM의 객체들을 볼 수 있어요. (시간이 되시면 vanila로 아무거나 html만들어서 동작시켜보세요!)
```javscript
document.styleSheets
```
따라서 우리가 보는 브라우저의 화면은 DOM + CSSOM이 결합된 결과라고 볼 수 있어요. 이 결합을 통해 `Render Tree`를 만들어냅니다. DOM의 각 노드가 CSSOM에서 계산한 값들을 기반으로 각 요소의 `style`을 포함하는 `Render Object`를 만들어 `Render Tree`에 붙이게 되는거죠.

```text
Render Tree
│
├── body (background-color: blue)
│   ├── header
│   │   └── h1 (display: flex, text: "Hello, World!")
│   └── main
│       └── p (text: "안녕하세요?")
```
물론 DOM에 모든 요소들이 포함되지는 않아요. 화면에 나타내야 할 것만 들어갑니다. 즉, `h1 → display:none` 이라면 제외됩니다.

### 브라우저의 동작
![image](https://github.com/user-attachments/assets/5a72624a-eeac-459d-99e5-8ffa33004bc7)

DOM과 CSSOM은 브라우저들이 제공하기로 표준화 되어있는 기능중 일부인데요. 이 “표준화 되어있는 기능”을 [WebAPI](https://developer.mozilla.org/ko/docs/Web/API)라고 불러요. WebAPI는 즉, 브라우저가 오류없이 기능하다면 사용자가 JS를 통해 사용할 수 있도록 제공해야하는 기능을 의미합니다!

대표적으로는 event,timer,webStorage,Canvas,AJAX등이 있어요.

이렇게 DOM과 CSSOM 그리고 브라우저가 Composing 되기까지의 과정을 적어봤어요! 😄 이번주 미션도 수고하셨고 금요일에 보는 시험 잘 보시길 바랄게요👐🏻 삭제해야될 코드에 대해서만 코드 리팩토링 진행해주시면 될 것 같아요! 리팩토링 후 멘션 걸어주세요! 고생하셨습니다😄

2024-11-24 08:29 UTC, Indigochi1d commented on src/style/HeaderStyle.js
주석처리된 코드를 사용하지 않는다면 지워주시는게 좋을 것 같아요

2024-11-24 08:29 UTC, Indigochi1d commented on src/style/RestaurantListStyle.js
>      display: -webkit-box;
-webkit은 어떻게 쓰는걸까요? 이 [링크](https://developer.mozilla.org/ko/docs/Glossary/WebKit)를 정독 해 보시면 좋을것 같이요

2024-11-24 08:29 UTC, Indigochi1d commented on src/App.css
> +}
요구사항 명세에 아래처럼 나와있었어요. 그대로 잘 적용해주셨네요!
![image](https://github.com/user-attachments/assets/bc814068-ac13-44ee-8f42-341b7067f8fd)

:root 에서 color styling선언을 통해 전역으로 색 해시값을 문자로 나타내게 할 수 있었는데요. 만약 이것을 `styled-components` 의 기능 중 하나를 사용해서 전역으로 선언할 수 있다면 어떤 기능을 사용하면 될까요? 🤔  

> [!NOTE]
힌트는 저희 스터디 시간에 공유했던 내용중에 있습니다! 답을 찾으신 후 시간이 괜찮으시다면 그걸 토대로 리팩토링해주셔도 되고 다음미션과 현생이슈로 할일이 너무 많다면 이대로 해주셔도 무방해요😆

2024-11-24 08:29 UTC, Indigochi1d commented on src/style/AddRestaurantModalStyle.js
> +  }
👍🏻 
props를 사용할 수 있는데 잘 이용해 주셨군요!

2024-11-24 08:29 UTC, Indigochi1d commented on src/style/HeaderStyle.js
> + */
안 쓰는 부분은 지우는게 좋아보입니다!

2024-11-24 08:29 UTC, Indigochi1d commented on src/style/RestaurantListStyle.js
> +    -webkit-box-orient: vertical;
이건 어떤 기능을 하나요? 그리고 이 기능을 모든 브라우저에서 지원할까요?

2024-11-24 08:29 UTC, Indigochi1d commented on src/components/RestaurantDetailModal.jsx
> +} from "../style/RestaurantDetailModalStyle";
스타일 컴포넌트들을 분리해서 관리해주고 계시는군요👍🏻 아주 좋은 방법입니다. 저는 보통 한곳에 몰아쓰긴 하는데 이렇게 하는 게 모니터가 크거나 투 모니터일땐 더 좋은 것 같아요. 다음 프로젝트에선 저도 이런 방식을 채용해봐야겠네요 🤔

2024-11-27 05:34 UTC, ye6194 commented on src/style/HeaderStyle.js
엇 주석 다 지운줄 알았는데 남아있었네요. 지우겠습니다

2024-11-27 05:37 UTC, ye6194 commented on src/style/HeaderStyle.js
> + */
넵 지우겠습니다!

2024-11-27 08:52 UTC, ye6194 commented on src/style/HeaderStyle.js
다 지운줄 알았는데 깜빡했네요😮

2024-11-27 08:54 UTC, ye6194 commented on src/App.css
> +}
`GlobalStyle`로 전역 스타일을 정의할 수 있습니다!
일단 이렇게 해놓고 나중에 리팩토링 하겠습니다🥲

2024-11-27 10:00 UTC, ye6194 commented on src/style/RestaurantListStyle.js
> +    -webkit-box-orient: vertical;
- `-webkit-line-clamp`: 텍스트 줄 수를 제한합니다. 여기서는 2줄까지만 표시되도록 합니다.
- `-webkit-box-orient`: 요소의 콘텐츠 방향을 지정합니다. 여기서는 vertical로 표시되어 있기 때문에 세로로 쌓입니다.

웹킷은 크롬, 엣지, 사파리 등의 브라우저에서 지원되고 파이어 폭스같이 지원되지 않는 브라우저도 있습니다!

2024-11-27 10:00 UTC, ye6194 commented on src/style/RestaurantListStyle.js
> +    -webkit-box-orient: vertical;
- `-webkit-line-clamp`: 텍스트 줄 수를 제한합니다. 여기서는 2줄까지만 표시되도록 합니다.
- `-webkit-box-orient`: 요소의 콘텐츠 방향을 지정합니다. 여기서는 vertical로 표시되어 있기 때문에 세로로 쌓입니다.

웹킷은 크롬, 엣지, 사파리 등의 브라우저에서 지원되고 파이어 폭스같이 지원되지 않는 브라우저도 있습니다!

2024-11-27 10:12 UTC, ye6194 commented on src/style/RestaurantListStyle.js
>      display: -webkit-box;
webkit 전용 속성을 사용하는 경우 앞에 `-webkit-`을 붙여야 합니다👀

2024-11-27 23:52 UTC, Indigochi1d approved these changes

2024-11-27 23:53 UTC, merged