[adv-1단계] 김준수 미션 제출합니다.
greedy-team/self-paced-react-advanced pull request #3
Opened 2024-11-20 08:07 UTC by gogo1414

## 개요
안녕하세요, 리뷰어님😊
이번 주차 미션은 참 많이 헤맸습니다... 제가 미션을 기존에 잘못 포크해놔서 그 미션인 줄 알고 진행하다가 너무 어려워서 깜짝놀랐네요..
아무튼 이런 저런 고비를 거쳐 늦었지만 제출해봅니다!

## 호기심
`styled-components` 를  처음 다뤄봤는데 props도 이용할 수 있다는 점이 매우 신기했네요! 특히 동적으로 스타일링을 적용하는게 어떻게 기능이 작동되는지 그 점도 궁금하고요!!

## 작업내용

1. 기존 css 파일 적용된 것들을 `styled` 로 대체했습니다!
2. `isRequired`를 사용해서 동적으로 `::after`를 적용했습니다.

## 아쉬운 점
원래 `styled-components`를 적용해보면서 기존에 boolean 값으로 모달 실행 자체를 판단하는 것을 바꿔보려고 했는데, 계속 시도 해봐도 잘 안되서 우선적으로 문제를 제출해봤습니다..

 ## 작동 화면
<img width="976" alt="스크린샷 2024-11-20 오후 5 02 16" src="https://github.com/user-attachments/assets/7bc8fa26-f7e8-4b8d-8444-b6739efb0ab6">
<img width="976" alt="스크린샷 2024-11-20 오후 5 02 34" src="https://github.com/user-attachments/assets/27a1a05c-cdf3-457f-89f7-fe1c90cc226f">
<img width="976" alt="스크린샷 2024-11-20 오후 5 02 53" src="https://github.com/user-attachments/assets/403a5f7d-1635-45f6-9abb-84d79412d8e9">

## 데이이터 흐름도
<img width="661" alt="스크린샷 2024-11-20 오후 5 06 30" src="https://github.com/user-attachments/assets/532696a3-7131-4586-91dc-92670dc80f7a">

## 느낀점
점점 CSS 적용하는건 재밌으면서 화가나네요... 작성을 했는데 작동이 안될 때 분노하게 됩니다.. 그리고 `className`에 -가 어떤건 1개 있고 어떤건 2개 있던데 통일하면 어떨까 싶기도 하구요..

2024-11-21 07:53 UTC, Songhyejeong reviewed
안녕하세요 준수님! 
이번 미션 처음에 다른 미션 진행하셨다고 하셔서ㅠㅠㅋㅋㅋㅋㅋ 그래도 마무리 잘 하신거 같아서 다행입니다..! 
저도 css할 때가 제일 재밌는데 준수님도 css 재미를 이번 미션을 통해서 느끼신 거 같아서 좋습니다!

###  동적으로 스타일링 적용 기능
그리고 styled-compoents가 props를 받아서 동적으로 스타일링 되는 기능을 제가 준수님 코드에서 
boolean값으로 모달 여닫기를 추가했었는데 그걸로 간단하게 말씀드려볼게요!

준수님께서 작성하신 CSS 코드를 통해서 styled-component는 CSS-in-JS 방식을 사용해서 스타일을 고유하게 식별하기 위해 **해시 값**을 생성합니다. 
```
const RESTAURANT_WRAPPER = styled.li`
    display: flex;
    align-items: flex-start;
    padding: 16px 8px;
    border-bottom: 1px solid #e9eaed;
`;
```

예를 들면 준수님 코드에서 이 값이 f0vcqH로 저장되네요!
<img width="200" alt="Screenshot 2024-11-21 at 4 40 55 PM" src="https://github.com/user-attachments/assets/3c88e3f7-b7e2-4e68-8183-1be49055744f">

그리고 이 props 값이 바뀔 때마다 해시값이 바뀌며 다르게 style이 다르게 인식되는 거 같습니다!
<img width="200" alt="Screenshot 2024-11-21 at 4 44 57 PM" src="https://github.com/user-attachments/assets/e51e7236-bd9c-435c-8b87-37800091a6a4">


<img width="200" alt="Screenshot 2024-11-21 at 4 45 14 PM" src="https://github.com/user-attachments/assets/4b82ebb5-893e-49f2-96ee-7346667a6214">

여기서 aside의 두 번째 div의 해시 값을 보시면 될 거 같습니다!

**블로그**
저도 이 블로그 참고해서 설명 드렸는데 좋은 내용이 많은 거 같아서 자세한 내용은 이 블로그 보시면 좋을 거 같아서 공유드립니다!
[https://joong-sunny.github.io/javascript/styled-components/](url)

이번 미션도 수고하셨습니다 👍

2024-11-21 07:53 UTC, Songhyejeong commented on src/components/Aside/RestaurantDetailModal.jsx
> +        <Modal title={restaurant.name} onClose={onChangeDetailModal}>
질문 주신 거 중에 Modal 상태를 받아서 여닫는 방법은 

**App.jsx**
```
      <aside>
          <RestaurantDetailModal 
          isModalOpen ={isModalOpen}
            restaurant={clickedRestaurantItem} 
            onChangeDetailModal={() => toggleModal("detail", false)}
          />
          <AddRestaurantModal
           isModalOpen ={isModalOpen}
            onFormSubmit={(event) => toggleModal("add", false, null, event)}
            onChangeAddModal={() => toggleModal("add", false)}
          />
      </aside>
```
이렇게 App.jsx에서 isModalOpen의 상태를 각각 넘겨 주고

**RestaurantDetailModal.jsx**

```suggestion
        <Modal isModalOpen = {isModalOpen.detail} title={restaurant.name} onClose={onChangeDetailModal}>
```
각각의 상태 값을 isModalOpen으로 넘겨주면

**Modal.jsx**


```
import styled from 'styled-components';

const MODAL_WRAPPER = styled.div`
  display: ${(props) => (props.isModalOpen ? 'block' : 'none')};
`;

const MODAL_BACKDROP = styled.div`
  position: fixed;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background: rgba(0, 0, 0, 0.35);
`;

const MODAL_CONTAINER = styled.div`
  position: fixed;
  bottom: 0;
  width: 100%;
  padding: 32px 16px;
  border-radius: 8px 8px 0px 0px;
  background: var(--grey-100);
`;

const MODAL_TITLE = styled.h2`
  margin-bottom: 36px;
  font-size: 20px;
  line-height: 24px;
  font-weight: 600;
`;

function Modal({ isModalOpen, children, title, onClose }) {
  return (
    <MODAL_WRAPPER isModalOpen={isModalOpen}>
      <MODAL_BACKDROP onClick={onClose}></MODAL_BACKDROP>
      <MODAL_CONTAINER>
        <MODAL_TITLE>{title}</MODAL_TITLE>
        {children}
      </MODAL_CONTAINER>
    </MODAL_WRAPPER>
  );
}

export default Modal;
```
이렇게 공통 컴포넌트인 Modal에서 boolean 값을 props로 넘겨서 직접 바꿀 수 있습니다!

2024-11-21 07:53 UTC, Songhyejeong commented on src/components/Aside/RestaurantDetailModal.jsx
> +    //font-weight: 400;
이 줄은 지워도 될 거 같네요!

2024-11-22 10:00 UTC, gogo1414 commented on src/App.css
넵, 감사합니다!

2024-11-22 10:01 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +const FORM_ITEM = styled.div`
사실 처음 손가는게 스네이크케이스라 그렇게 작성했었어요! 
오늘 스터디를 듣고 보니 컴포넌트랑 유사한 부분이 많아서 파스칼케이스로 작성하는 것이 더 좋을거 같네요!

2024-11-22 10:03 UTC, gogo1414 commented on src/components/Aside/RestaurantDetailModal.jsx
> +        <Modal title={restaurant.name} onClose={onChangeDetailModal}>
옷 너무 친절하게 알려주셔서 감사합니다!😊

2024-11-22 10:04 UTC, gogo1414 commented on src/components/Aside/RestaurantDetailModal.jsx
> +    //font-weight: 400;
중복되는 내용이 종종 있길래 고민했는데, 알려주셔서 감사합니다👍

2024-11-22 10:25 UTC, gogo1414 commented on src/components/Aside/RestaurantDetailModal.jsx
> +        <Modal title={restaurant.name} onClose={onChangeDetailModal}>
해보려고 하는데, 잘 안되긴 하네요.. 다른 수정할 부분도 많은거 같아요!....😂_

2024-11-23 15:03 UTC, wzrabbit requested changes
@gogo1414 👋🏻 

이번에는 스타일링 기법 중 하나인 `CSS-in-JS`, 그 중에서도 잘 알려진 라이브러리 중 하나인 `styled-components` 를 적용해 보는 미션이군요! 

JavaScript와 css를 서로 긴밀하게 결합시키고 컴포넌트의 상황에 따라 동적으로 여러 속성을 적용하는 것에 참 강한 라이브러리죠.

JavaScript를 이용해 스타일들을 조절할 수 있다는 것은 코드를 재활용하거나, 코드를 변수처럼 여러 곳에 사용하기에도 용이하다는 것을 의미해요. 잘 관리하면 css를 순수하게 사용했을 때보다 유지보수에 용이하고 스타일들을 모듈화해서 잘 정리할 수도 있을 거에요.

## 1️⃣ 리뷰

리뷰 시에는 기존 css 코드들이 스타일 컴포넌트의 형태로 각 요소에 적용되어 잘 마이그레이션되었는지를 위주로 확인해 보았어요. 요소별로 스타일을 적절히 나눠 잘 활용해 주신 것 같아요. 

`isRequired` prop을 스타일 컴포넌트에서 사용할 수 있도록 구현해 폼에서 조건에 따라 서로 다른 UI를 보여주도록 한 부분도 잘 보았어요. 핵심적인 기능인데 잘 구현하셨어요. 여기에 더해 스타일 컴포넌트에서 다뤄지는 props에 대해 꼭 챙겨가야 할 점이 있다고 생각해 관련하여 코멘트 달아드렸어요.

반영해 주신 것 외에도, `styled-components`는 적용할만한 여러 기능들이 있는데, 미션이 간단해 놓치는 부분이 많을 것이라고 생각했어요. 혹시 이후에 더 학습을 하실 것을 생각해, 더 적용할 수 있는 부분들을 코멘트했지만, 당장 반영하라고 드린 요구사항들은 아니므로 인사이트의 일부라고 생각해주셨으면 좋겠어요.

"아쉬운 점" 에 적어주신 문제의 경우, 어떤 것을 하고 싶으신지 보다 구체적으로 설명해주신다면 저도 해결 방법에 대해 고민해 볼 수 있을 것 같아요. 특히 동작하지 않는 코드를 올려주시면 더 좋을 것 같습니다.

그럼, 코멘트로 의견 공유드렸으니 준수님도 의견을 들려주세요! 화이팅~

2024-11-26 08:52 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +    `}
> 추가로, 이러한 에러들은 React에서 경고 차원으로 보내는 에러이기 때문에 애플리케이션이 화면에 나타나지 않는 등 크래쉬가 나지 않게 됩니다. 그렇기 때문에, 항상 개발자 도구를 열어 이러한 경고 차원의 에러들이 발생하는지를 꼼꼼하게 확인해 주시면 더 완성도가 높은 애플리케이션을 만드실 수 있을 것이라 생각됩니다!

경고 차원으로 나타나는 문구에 대해 인식을 못했었는데 스타일 컴포넌트를 사용할 때 DOM에 반영되는 여부에 대해 생각해야 하는 점을 못했네요.. 단순히 CSS적인 요소만을 생각했었는데 고려해야 할 부분이 있었네요!

> 본 컴포넌트에서는 isRequired 가 사용자 정의 속성이고, DOM에 나타나더라도 아무 작용을 안 하는, 스타일 컴포넌트 내부에서만 쓰이도록 설계된 prop 처럼 보입니다. 제가 의도를 올바르게 예상했나요?

- "*"를 표시하는 기능이 가상 요소로 작동하기 때문에 DOM에 나타나도 아무 작용을 안하도록 설계된 prop이 맞습니다!

조금 궁금한 점이 제가 작성한 코드도 props 앞에 $를 붙이고 있는데 2번의 transient props 방식이 적용된게 아닌 잘못된 방식인걸까요??

2024-11-26 08:57 UTC, gogo1414 commented on src/components/Main/CategoryFilter.jsx
> +    }
> & 은 무엇을 의미할까요?

- &은 내부의 특정 요소를 참조하기 위해 사용되는 글자(명령어?)라고 생각합니다.

> & 은 별도의 라이브러리가 없는 순수한 CSS에서도 사용할 수 있는 문법일까요? 그렇다면, 어떻게 작동할까요?

- 순수한 CSS에서는 사용이 안될거 같습니다. 순수 CSS에서는 className으로 지정하면 되는 방식을 사용하면 된다고 생각해서 사용이 불가능하다고 생각이 드네요.. JS를 지원하는 CSS 혹은 특정 라이브러리에서 사용이 가능한게 아닐까요?

> & select 는 무엇을 의미할까요?

- 내부 하위 요소 중 select를 참조하기 하라는 의미라고 생각합니다.

2024-11-26 09:01 UTC, gogo1414 commented
많은 내용 알려주셔서 감사합니다!

리뷰 반영은 최대한 진행해봤으며, 질문도 1가지 남겨봤습니다! 
그 외에 나머지 알려주신 것들은 스스로 진행해보다가 문제에 부딪히면 질문해보도록 하겠습니다!

[리뷰 반영](https://github.com/greedy-team/self-paced-react-advanced/pull/3/commits/7d2947d04ad9180ac5d613cf2572e99a5d9dc61a)

2024-11-27 13:12 UTC, wzrabbit approved these changes
수고하셨어요~ ✅ 👍🏻 

styled-component를 비롯한 라이브러리들은 1주일 만에 모든 기능을 섭렵하기는 어려울 겁니다😄이번 미션의 취지는 CSS의 단점을 생각해 보고, 이에 대해 개발자들이 어떤 해결 방법을 생각해보았는지 라이브러리로 느껴보는 것이며, 기본적인 기능들을 체험해 보는 것이었을 거라고 생각해요. CSS-in-JS 가 뭔지 간략하게라도 설명하실 수 있고 이런 느낌을 피부로 느끼셨다면 그것으로 충분합니다

그러니 이후 실제 프론트엔드 개발에서 더 많은 기능들을 접해보시기 바래요

이후의 미션들에서도 더 다양한 라이브러리 및 기술들을 접하실 거에요, 폭넓은 경험을 하시길 바라겠습니다 💪🏻

2024-11-27 13:12 UTC, wzrabbit commented on src/components/Main/CategoryFilter.jsx
> +                        key={category.id} value={category.name}>{category.name}</option>
Prettier 라이브러리의 도입도 한 번 생각해보세요!
- https://discordapp.com/channels/1277285790270885889/1277617980146192435/1311234095707328512

2024-11-27 13:12 UTC, wzrabbit commented on src/components/Header/Header.jsx
> +    & img {
잘 반영해주셨어요 ✅

2024-11-27 23:49 UTC, merged