[adv-2(1)단계] 박예은 미션 제출합니다.
greedy-team/self-paced-react-advanced pull request #4
Opened 2024-11-25 17:35 UTC by ye6194

안녕하세요 리뷰어님!

이번 미션은 context API를 쓰는 미션이였는데요. 리뷰어님은 이번 미션 어떠셨나요? 
저는 context API가 뭔지만 대충 알고 실제로 써보는건 처음이었는데 어려웠던 것 같아요.
공식문서나 다른 사람의 블로그에 있는 예제를 보면 다크 모드/라이트 모드 변환이나 css를 바꾸는 간단한 예제라 이해가 갔는데 제 코드는 useState, useEffect, API가 섞여있으니 어떻게 코드를 짜야할 지 감이 잡히지 않았어요🥲
어찌저찌 미션을 구현하긴 했지만 아직 많이 헷갈리네요...

##  구현 내용
- props를 사용하지 않고 context API를 사용하도록 수정
<br>

## context API를 사용하는 이유
- 전역적인 상태나 데이터를 쉽게 공유하기 위해서 사용합니다.

### props를 사용하는 방법과의 trade-off
context API 사용 시 
- 장점
   - Props Drilling을 피할 수 있습니다.
   - 전역 상태를 쉽게 공유 및 관리가 가능합니다.
- 단점
   - 규모가 작은 앱의 경우 오히려 더 복잡해집니다. 
<br>
 
## 구조
![image](https://github.com/user-attachments/assets/1f036f04-5c29-4527-a2ed-8c70f71b058f)
<br>

## 스크린샷
![localhost_5173_ (2)](https://github.com/user-attachments/assets/86c81cfa-7b02-4912-b746-a4124e2d2257)

2024-11-28 03:40 UTC, Songhyejeong reviewed
안녕하세요 예은님 !
context API는 처음이라고 하셨는데 잘 구현해주신거 같아요! `Consumer`대신 `useContext`를 사용해주신 걸 보니 얼른 제 코드를 리팩터링 하고 싶은 생각이 드네요! 그리고 비슷한 기능을 하는 것들을 묶어서 한 번에 객체로 관리하신 것도 인상 깊었습니다! 
제 코드에도 적용 해보고 싶어요.

그리고 props를 사용하는 방법과의 trade-off에서 적어주신 것도 공감되었어요
전역 상태관리 라이브러리를 사용하면 데이터 처리를 한 곳에서 할 수 있다는 장점이 있지만 데이터의 흐름을 알기 어렵고 코드의 결합도가 높아지는 단점이 있어서 필요한 곳에 알맞게 쓰는 것도 중요할 것 같네요

이번 주차도 수고 많으셨습니다!🙂

2024-11-28 03:40 UTC, Songhyejeong commented on src/contexts/RestaurantListContext.jsx
> +  }, []);
```suggestion
  useEffect(() => {
   updateRestaurantList();
  }, []);
```
아래에 함수로 updateRestaurantList를 정의했으니 여기서도 불러와서 사용하면 좋을 거 같은데 예은님의 생각은 어떤가요..?!

2024-11-28 03:40 UTC, Songhyejeong commented on src/App.jsx
> +        {isAddModalOpen && <AddRestaurantModal />}
모달이 두 개여서 이 두개를 `addModal`과 `detailModal`처럼 구분할 수 있는 이름을 사용해도 좋을 것 같아요!
```suggestion
        {detailModal.isOpen && <RestaurantDetailModal />}
        {addModal.isOpen && <AddRestaurantModal />}
```

2024-11-28 03:40 UTC, Songhyejeong commented on src/main.jsx
> +  </StrictMode>
저는 main.jsx에서 Provider를 불러올 생각은 못했는데 `main.jsx`에서 Provider를 불러오면 App.jsx의 책임도 줄어들 거 같네요,..!
좋은 방법 같습니다 👍

2024-11-29 14:20 UTC, ye6194 commented on src/style/HeaderStyle.js
> +// export const HeaderContainer = styled.div`
앗 스텝1에서 리팩토링한건데 여기서는 안했네용 지우겠습니다!

2024-11-29 17:10 UTC, ye6194 commented on src/contexts/RestaurantListContext.jsx
> +  }, []);
지금 보니 그렇게 하니까 중복되는 코드를 줄일 수 있네요! 고치겠습니다

2024-12-02 03:51 UTC, Indigochi1d requested changes
안녕하세요 예은님! 리뷰가 조금 늦어진 점 죄송합니다ㅠ 주말에 할아버지 생신이셔서 거길 갔다오다보니 시간이 조금 미뤄졌네요ㅠ

이번 미션은 ContextAPI로 상태를 전역으로 관리함에 있었어요. 저희가 초록스터디를 하며 겪어왔던 `props drilling`문제를 해결하는 것이 주 목적이라고 12/22 스터디에 말씀드렸던 것 기억나시나요?  그런데 갑자기 ContextAPI 미션을 리뷰하는 12/29 스터디에는

>  `state-props 로 전달되는 방식` 은 나쁘기만 한게 아님!

이래버려서 `그럼 뭐 어쩌라는거지..?` 라는 의문을 가지셨을 수 도 있습니다ㅎ 저희가 스터디에서 이야기한 것처럼 규모가 작은 `점심 뭐 먹지` 와 같은 Application에는 사실 전역상태관리가 필요가 없고 state-props 로 전달하는 방식이 좀 더 자연스럽다고 이야기 나눴었어요. 물론 개발자의 편의 입장에선 전역으로 관리하는게 생각하기도 쉽고 편할 수 있겠지만 프론트엔드 개발의 목적이 `사용자의 편의` 이기 때문에 전역상태관리의 도입은 항상 잘 생각해봐야할 문제가 되는 것 같습니다. 프로젝트 할때도 항상 고민하게 되는 것 중 하나에요🤔 

### 1️⃣ 코드 리뷰
예은님의 코드를 보았을 때 contexts가 되게 깔끔하게 적힌 것 같다는 느낌을 받았습니다. 집으로 돌아오는 차 안에서 핸드폰으로 코드를 보고도 코드의 역할을 이해할 수 있을 정도로 읽기쉬운 코드였어요! 하나 의문점을 가지게 된 것은 `RestaurantListContext`에서 `useEffect` 와 `update` 함수가 적혀있었는데 저는 이 로직이 context가 아닌 뷰를 렌더링하는 실제 컴포넌트에서 이루어져야한다고 생각해요. 이 부분에 대해서는 코드 조각 리뷰에도 남겨놓았습니다! 답변해주시면 될 것 같아요! 

이번 미션하느라 수고 많으셨어요! 꿈에 그리던 종강까지 얼마 안남았네요😆기말고사 화이팅입니다!!

2024-12-02 03:51 UTC, Indigochi1d commented on src/contexts/RestaurantListContext.jsx
> +  };
예외처리가 안되어있는 것 같아요! 또한 문법적으로 상관없지만 `getRestaurantList` 가 async함수로 작성되어있기 때문에 `.then`을 사용한 프로미스 체이닝보단 `await`를 쓰는게 더 적합해 보이는데 시간이 되신다면 리팩토링 부탁드립니다!
```suggestion
  const updateRestaurantList = async () => {
    try {
      const data = await getRestaurantList(); 
      setRestaurantList(data); 
    } catch (error) {
      console.error("Failed to fetch restaurant list:", error); 
    }
  };
```

2024-12-02 03:51 UTC, Indigochi1d commented on src/contexts/CategoryContext.jsx
👍🏻

2024-12-02 03:51 UTC, Indigochi1d commented on src/contexts/ModalContext.jsx
> +}
👍🏻

2024-12-02 03:51 UTC, Indigochi1d commented on src/contexts/RestaurantListContext.jsx
> +  }, []);
`contexts`는 "전역으로 상태를 관리하는 도구"인데 이 안에서 `useEffect`를 통해 로직을 실행하는 것이 적절하진 않아보여요. 저는 이 `update`함수와 `useEffect실행` 역할이 `AddRestaurantModal` 컴포넌트의 책임이 아닐까 싶은데 예은님의 생각은 어떠신지 의견을 들려주세요!

2024-12-02 03:51 UTC, Indigochi1d commented on src/contexts/ModalContext.jsx
> +        setIsAddModalOpen,
객체의 속성에 `detailModal` 과 `setDetailModal`은 명시적으로 key-value를 작성해주셨고 아래 `isAddModalOpen`,`setIsAddModalOpen` 은 속성단축을 사용해주셨어요. 왜 그렇게 하신건지 이유를 알 수 있을까요? 🤔

2024-12-04 12:44 UTC, ye6194 commented on src/contexts/RestaurantListContext.jsx
> +  };
![image](https://github.com/user-attachments/assets/f76ddca5-9e8f-4e9a-9459-30cdc207d826)
예외처리는 step5 README에 "에러 상태는 고려하지 않습니다."라고 되어있어서 딱히 하지 않았었어요! 이번에 추가하도록 하겠습니다.
그리고 `.then`보다 `await`를 쓰는게 더 적합한 이유가 궁금합니다! 단순히 `async-await` 짝을 맞추기 위해서인가요? 아니면 다른 이유가 있나요?

2024-12-04 13:22 UTC, wzrabbit requested changes
@ye6194 반가워요~ 👋🏻 

이번 주차부터 state/props만 사용해 컴포넌트를 관리해보는 것에서 나아가 전역 상태들을 다루기 위한 기술들을 접하기 시작하는군요. PR에 적어주신대로 많이 생소하다고 느끼셨을 것이라 생각되며 충분히 이해됩니다. `styled-components`도 그렇고 처음 접했을 때 정체불명의 문법들이 꽤나 많은 것 같습니다.

## 1️⃣ 피드백
> 이해가 갔는데 제 코드는 useState, useEffect, API가 섞여있으니 어떻게 코드를 짜야할 지 감이 잡히지 않았어요

충분히 그러실 수 있을거라 생각합니다. 바닐라보다 헷갈리기도 할 거에요. 헷갈리신 부분이 있다면 Context API로 불러온 상태들도 상태니까, 비슷하게 취급하시면 될 것이라고 생각합니다. 메인테이너님이 달아주신 [Context API 측에서 다뤄야 하는 역할 및 책임 관련 코멘트](https://github.com/greedy-team/self-paced-react-advanced/pull/4#discussion_r1865178087)도 고민해 보실 만합니다.

> 어찌저찌 미션을 구현하긴 했지만 아직 많이 헷갈리네요...

미션대로 거의 모든 곳에 Context API를 도입하셨다면 헷갈리시는 것이 정상입니다. Context API를 과도하게 도입하면 생길 수 있는 문제 중 헷갈리는 데 영향을 줄 수 있는 단점들이 바로 "상태가 바뀌었는데 누가 바꿨는지 원천을 파악하기 힘들 수 있음" "데이터의 흐름을 파악하기 어려움" 입니다. 이 부분은 구조를 개선해보신다면 그나마 나아질 수 있을 것이라 생각합니다.

이후 Context API를 도입하실 때에 대한 조언을 드려보자면 무조건 바로 도입하시기보다는 일단 state/props 로 데이터 흐름을 제어해 보시되 심한 props drilling으로 인해 유지보수가 힘들거나, 너무 광범위한 레벨에서 많은 컴포넌트들이 이 상태를 사용해 여러 컴포넌트의 구조가 복잡해지거나 use-case에 맞지 않는 props들이 계속해서 생기고 있는 등, **불편함이 느껴지면 그 때** 도입해 보시면 어떨까 생각합니다.


## 2️⃣  리뷰
이번 미션의 목표는 프로젝트에 Context API를 적용하고, 이전 주차와 똑같이 작동하도록 프로젝트를 마이그레이션 시키는 것이 주요 목표로 보입니다. 따라서 이를 중점으로 두고 리뷰했습니다.

### ☪️ Context API 사용법/구현 측면
사용법을 잘 지키면서 잘 구현해 주신 것 같습니다.

- `Provider`와 `Context`를 선언하는 모듈
- 전역 상태들을 공유하고 프로젝트 내에서 광범위하게 사용하기 위해 `main` 모듈에 `Provider` 적용
- Context API의 상태를 필요로 하는 컴포넌트에 한하여 import하여 적용

을 잘 분리해서 적용해 주셨고, 선언한 모듈들을 `contexts` 디렉토리로 묶어 깔끔한 보일러플레이트를 갖춰주신 것 같아요. 이 부분에 대해서는 크게 드릴 코멘트가 없습니다. 👍🏻 

### ☪️ 기능 측면
아쉽게도 이전 미션과 다르게 올바르게 작동하지 않는 부분이 생긴 것 같습니다.
- 사용자가 카테고리를 골랐을 때 필터링된 레스토랑만을 보여줘야 하는데, 계속해서 레스토랑 전체가 보이는 것 같아요. 카테고리는 선택되는데 레스토랑의 목록이 반영되지 않는 것 같아요.

리뷰 요청 전 이러한 기본적인 기능들의 경우 확인하는지 직접 검토해주신다면, 보다 꼼꼼한 PR을 적으실 수 있을 거라고 생각합니다! 때로는 까다로운 심사위원처럼 작업하신 프로덕트를 실행하고 여러 조작을 해 보시길 바래요.

그리고, 특정 기능이 작동되지 않는데 고민과 시행착오에도 불구하고 해결되지 않을 때가 있을 거에요. 이 경우에는 PR에 작동하지 않는 기능이 있다고 리뷰어 분들께 알리는 것도 좋은 방법이 될 수 있을 거에요. 지금은 세 번째 바통을 받은 제가 이 문제를 확인했지만 직접 적어주셨다면 3명의 리뷰어 모두가 이 문제를 인지하고 고민 및 조언을 드릴 수도 있지 않았을까... 하는 아쉬운 마음도 듭니다 😢 

**기능의 올바른 작동** 은 곧 미션의 핵심 중 하나인 **마이그레이션의 성공** 을 의미하니, 이 부분은 남은 기간 동안 최선을 다해 개선에 힘써 주셨으면 합니다.

### ☪️ 목적 측면
(비어 있음)

여긴 비어 있습니다. 메인테이너님께서 미션을 주셨을 당시에는 **모든 곳에** Context API를 사용하라는 요구사항을 주신 것으로 알고 있어요. 그러나 구현하시면서 의외의 복잡함을 느끼셨을 거에요. 스터디 시간에서는 "정말 모든 곳에 Context API를 적용해야 하는 걸까?" 라는 의문에 대해서 이야기를 나누셨을 겁니다.

느끼신 대로겠지만, Context API를 사용하는 방법, 그리고 state/props를 사용하는 방법 중 어느 방법도 다른 한쪽을 대체하지 않아요. Context API를 도입한다고 해서 다른 방식을 아예 안 쓴다는 것은 아니라는 것입니다. 공구함에서 목적에 맞는 도구를 꺼내듯이 상태를 사용할 컴포넌트의 역할, 구조에 따라 적합해보이는 방법을 택할 뿐입니다.

**미션 수행 기간을 Context API를 사용하는 법을 익히는 시간으로 사용했다면, 리뷰어와의 시간은 Context API를 도입해야 할지에 대한 고민을 나누는 시간으로 활용해 봅시다.**

예은님께 아래의 의견을 나눌 것을 요청드리고 싶어요.

- Context API를 적용해주신 각 상태에 대해, 이 상태들을 Context API로 두는 것이 적합해 보인다고 생각하시나요, 아니면 state/props를 사용하는 기존 방식을 사용하는 것이 적합하다고 생각하시나요? 『각 상태에 대해』서요.

감이 잘 잡히지 않으시다면:
- PR을 적으실 때 Context API를 도입함으로써 챙길 수 있는 이점과 trade-off를 적어주신 것을 확인했어요. 잘 적어주셨더라고요. 이 장단점을 Context API 도입에 대한 근거로 활용해도 좋지 않을까요?
- 구현해 볼 시간이 충분하다면, state/props로도 사용해보고, Context API로도 사용해보고, ... 둘 다 시도해 보실 수도 있습니다. 무식하지만 확실한 방법이라고 생각해요.

답변이 완벽할 필요는 없어요. 예은님의 생각이 잘 담기면 되고요, 사실 몇몇 지양되는 방법을 제외하고는 이러한 기술들에 대해 구조를 어떻게 갖출지는 정말 정해진 정답이 없어요...!

그 외의 코멘트는 마이너하게 드렸습니다. 그만큼 저는 "기능 측면" 과 "목적 측면" 에 적힌 사항들을 우선적으로 고민해 보셨으면 하는 바램입니다.

그럼, 예은님의 의견 기다리고 있겠습니다! ✔️

2024-12-04 14:40 UTC, ye6194 commented on src/contexts/RestaurantListContext.jsx
> +  }, []);
저도 useEffect가 `RestaurantListContext`에 있는게 신경쓰이긴 했는데 역시 여기 있는게 적절하지 않는 거였군요.
useEffect는 `AddRestaurantModal`에 옮겼고, update 함수는 `App`에서 안쓰니까 제대로 작동이 안돼서 update 함수를 `RestaurantListContext`에 남겨두고 `App`, `AddRestaurantModal`에서 import 해오는 형식으로 바꿨어요.

근데 이전 코드를 보면 App에 update함수가 없어도 작동이 됐었는데 지금은 왜 안되는지 모르겠네요..

2024-12-04 14:43 UTC, ye6194 commented on src/contexts/ModalContext.jsx
> +        setIsAddModalOpen,
잉?? 굳이 `detailModal: detailModal, setDetailModal: setDetailModal,`로 쓸 필요가 없었는데 저도 과거의 제가 왜 이렇게 썼는지 모르겠네요😅 `detailModal`, `setDetailModal`로 고쳤습니다

2024-12-04 14:57 UTC, ye6194 commented
안녕하세요 범수님!!

흔들리는 차 안에서 노트북도 아닌 핸드폰으로 코드를 보셨다니... 멀미 안 나셨나요..? 열정이 대단하신 것 같아요ㅋㅋㅋ👍

> RestaurantListContext에서 useEffect 와 update 함수가 적혀있었는데 저는 이 로직이 context가 아닌 뷰를 렌더링하는 실제 컴포넌트에서 이루어져야한다고 생각해요. 

useEffect는 RestaurantListContext에서 AddRestaurantModal로 옮겼지만 update함수는 RestaurantListContext에 그대로 두고 App과 AddRestaurantModal에서 쓰고 있어요. 위에도 쓴 내용이지만, update함수를 App에서 없앨 수 있는 방법이 없을까요?

이번에도 리뷰하시느라 수고 많으셨습니다!

2024-12-04 15:24 UTC, ye6194 commented on src/App.jsx
> +import { ModalContext, ModalProvider } from "./contexts/ModalContext";
eslint 설정 파일을 다음과 같이 작성해놔서 항상 사용하지 않는 모듈에 경고가 떴었는데
```
rules: {
    ...
    "no-unused-vars": "warn",
  },
```
어느 순간부터 안뜨더라구요. 의천님의 리뷰를 보고 eslint를 살펴보니 정확하진 않지만 버전이 달라져서 eslint가 적용되지 않았던 것 같아요. 처음에 어떻게 할지 몰라서 계속 헤매다가 결국 eslint의 버전을 내리니까 해결이 됐고, 사용되지 않는 모듈들을 편하게 지울 수 있었어요. 의천님 덕분에 다시 eslint가 제대로 적용됐네요🙇🏻‍♀️

2024-12-04 15:27 UTC, ye6194 commented on src/components/RestaurantList.jsx
> +  const { restaurantList: restaurants } = useContext(RestaurantListContext);
거창한 뜻이 있던건 아니고 
```js
return (
    <RestaurantListContainer>
      <ul className="restaurant-list">
        {restaurants.map((restaurant) => (
          <Restaurant key={restaurant.id} onClick={() => handleRestaurantClick(restaurant)}>
            ...
```
원래 이렇게 레스토랑 목록을 담는 배열의 이름이 restaurants이었어서 `restaurantList: restaurants`라고 썼어요. 그냥 하나로 통일하는게 나을까요?

2024-12-04 15:41 UTC, ye6194 commented on src/main.jsx
> +    </CategoryProvider>
## 답변

1. 
- `Provider`는 contextAPI를 이용해 하위 컴포넌트들에게 전역적으로 데이터를 제공하기 위해 사용해요.
- `<~~Provider>`를 사용하지 않는다는게 Provider 태그 없이 context를 사용한다는 의미 맞나요?? 이건 감이 안잡혀서 찾아봤는데 createContext()로 정의한 기본값만 사용하게 된다고 해요.
<br>

2. `Provider` 하위의 컴포넌트들만 컨텍스트 데이터를 구독할 수 있어요. 그렇게 되면 전역 상태 관리를 할 수 없으므로 contextAPI를 쓰는 의미가 없어진다고 생각합니다.

2024-12-04 16:01 UTC, ye6194 commented
안녕하세요 의천님!!

> 사용자가 카테고리를 골랐을 때 필터링된 레스토랑만을 보여줘야 하는데, 계속해서 레스토랑 전체가 보이는 것 같아요. 카테고리는 선택되는데 레스토랑의 목록이 반영되지 않는 것 같아요.

헉... 당연히 카테고리를 골랐을 때 필터링 될 줄 알았는데 작동되지 않았었네요. self-paced-react-advanced로 넘어오면서 레스토랑 추가가 잘 되는지만 테스트해봤던 것 같아요. 다음부터는 모든 기능을 꼼꼼히 확인해 봐야겠습니다.
<br>

> Context API를 적용해주신 각 상태에 대해, 이 상태들을 Context API로 두는 것이 적합해 보인다고 생각하시나요, 아니면 state/props를 사용하는 기존 방식을 사용하는 것이 적합하다고 생각하시나요? 『각 상태에 대해』서요.

'점심 뭐 먹지' 프로젝트는 규모가 작기 때문에, props drilling이 발생하지 않고 있어요. 그래서 각 상태들을 꼭 Context API로 두지 않고 props를 전달하는 방식만으로도 충분하다고 생각합니다. 만약 규모가 커진다면 상태들을 Context API로 두는게 훨씬 편할 것 같아요🙂

이번에도 리뷰하시느라 수고 많으셨습니다!

2024-12-05 06:01 UTC, Indigochi1d commented on src/contexts/RestaurantListContext.jsx
> +  };
`async-await`을 쓰는 이유는 코드작성의 일관성 부분에서 말씀드린거긴합니다!

2024-12-05 06:02 UTC, Indigochi1d commented on src/contexts/RestaurantListContext.jsx
> +  }, []);
😢

2024-12-06 12:30 UTC, wzrabbit approved these changes
@ye6194 👍🏻 

수고하셨습니다! Context API 도입해 대해서 충분히 고민해보셨기를 바랍니다.

> 헉... 당연히 카테고리를 골랐을 때 필터링 될 줄 알았는데 그렇지 않았었네요. self-paced-react-advanced로 넘어오면서 레스토랑 추가가 잘 되는지만 테스트해봤던 것 같아요. 다음부터는 모든 기능을 꼼꼼히 확인해 봐야겠습니다.

좋습니다 👍🏻 더 활약하는 모습 기대하겠습니다! 리팩터링 이후 다시 확인해봤는데 이번에는 잘 동작합니다, 수고하셨습니다

> '점심 뭐 먹지' 프로젝트는 규모가 작기 때문에, props drilling이 발생하지 않고 있어요. 그래서 각 상태들을 꼭 Context API로 두지 않고 props를 전달하는 방식만으로도 충분하다고 생각합니다. 만약 규모가 커진다면 상태들을 Context API로 두는게 훨씬 편할 것 같아요🙂

사실 간단명료하면서 핵심적인 답변이기도 하네요, 작은 규모의 애플리케이션이라면 처음에 말씀해주셨던 단점들이 사실 잘 발생하지 않을 것이기도 합니다. 이후 애플리케이션에서  전역 상태를 고려하실 때 여러 생각들을 해 보시길 바래요.

수고하셨습니다, 시험공부 열심히 해요~

2024-12-06 12:43 UTC, ye6194 commented on src/main.jsx
> +    </CategoryProvider>
>  특정 범위의 광범위한 컴포넌트들에게만 값을 공유해야 하는 경우에는 이 방법도 쓰일 수 있어요. 
아 이런 경우를 고려 못했네요!! 이 경우라면 충분히 쓰일 수 있겠네요.

2024-12-06 12:51 UTC, ye6194 commented on src/components/RestaurantList.jsx
> +  const { restaurantList: restaurants } = useContext(RestaurantListContext);
아 이거 카테고리 선택 시 필터링 안되는 문제 해결하면서 `restaurantList`로 고쳤는데 커밋 메시지에 까먹고 안적었네요..!!

2024-12-06 12:52 UTC, ye6194 commented on src/components/AddRestaurantModal.jsx
헉... 다음 미션 때 해보겠습니다!

2024-12-06 12:55 UTC, ye6194 commented
> Context API는 사용하기 굉장히 유혹적입니다! 하지만, 이는 남용하기 쉽다는 것을 의미하기도 합니다. 여러 계층에 걸쳐 props를 통과시켜야 한다는 점 자체가 Context API를 사용해야 하는 것을 의미하지는 않습니다.

오 의외군요... 좋은 글 잘 읽었습니다🙇🏻‍♀️

2024-12-06 13:49 UTC, merged