[adv-2.1단계] 김준수 미션 제출합니다.
greedy-team/self-paced-react-advanced pull request #5
Opened 2024-11-26 11:59 UTC by gogo1414

## 개요
안녕하세요, 리뷰어님😊
이번 주차 미션은 어떠셨나요? 저는 공식 문서를 보고 살짝 이해가 안갔었는데 더북 홈페이지 내용을 보고 조금 이해가 갔답니다... 사실 정확하게 이해하지는 못했어요 그냥 따라서 학습해본거라고 생각이 드네요..
여하튼 작동은 잘되니 한번 검토 부탁드릴게요!

## 호기심
이번 주차는 저도 잘 이해를 못해서 어렵네요.. 호기심이라기 보다 `toggleModal` 설정을 해제해서 다르게 적용해야할 지 고민했었어요 RestaurantProvider를 main.jsx 에 적용해서 그 문제는 피했지만(또 다른 적용 방법이 있긴 했겠죠..?) 기존 코드를 교체할 때가 왔나 싶었답니다..

## 작업내용
- `contexts` 폴더를 만들었습니다.
- `RestaurantContext.jsx` 파일을 만들었습니다.
- `App.jsx`에서 전달할 상태, 함수 값들을 모두 `RestaurantContext`로 옮겼습니다!
- `App.jsx`와 하위 컴포넌트들을 분할 화면으로 보며 코드를 고쳐가며 적용했습니다.
- 전주차 미션에서 발생했던 `isRequired`의 문제를 `$` 적용하여 해결했습니다!

## 참고자료
[더 북](https://thebook.io/080203/0520/)
[리액트 공식 홈페이지](https://ko.legacy.reactjs.org/docs/context.html) - 한글 번역이 조금 이상한거 같아요.. 이해하기 어려웠네요ㅠ

## 아쉬운점
뭔가 동작 과정을 정확하게 이해하지 않고 진행한 느낌이라 조금 찝찝하네요😂

## 작동 화면
<img width="976" alt="스크린샷 2024-11-26 오후 8 51 28" src="https://github.com/user-attachments/assets/16a5b7a4-6c96-49b8-9b3c-0103c3116e7b">
<img width="976" alt="스크린샷 2024-11-26 오후 8 51 38" src="https://github.com/user-attachments/assets/72064ffb-1cb8-47b6-a96d-a26c636450ba">
<img width="976" alt="스크린샷 2024-11-26 오후 8 51 45" src="https://github.com/user-attachments/assets/db6cb18a-c0aa-4654-9d8d-1da55f8b95c7">
<img width="976" alt="스크린샷 2024-11-26 오후 8 51 53" src="https://github.com/user-attachments/assets/60f3a81f-c2bc-4708-83fc-10656d938b33">
<img width="976" alt="스크린샷 2024-11-26 오후 8 52 11" src="https://github.com/user-attachments/assets/4510769b-0f24-4ac2-b5ce-3fdc6c121e15">

## 데이터 흐름도
(추후 추가해보도록 하겠습니다!)

## 느낀점
확실히 props를 하위 컴포넌트의 하위컴포넌트의 ... 으로 전달하면서 관리하지 않아도 되니 너무 편했어요!

2024-11-27 11:11 UTC, ye6194 commented on src/contexts/RestaurantContext.jsx
> +export const useRestaurantContext = () => useContext(RestaurantContext);
오... 신기한 문법이네요!

2024-11-28 07:46 UTC, gogo1414 commented on src/main.jsx
> +    </RestaurantProvider>
[StrictMode](https://ko.react.dev/reference/react/StrictMode) 예은님이 보내주신 사이트를 보니 최신 버전의 리액트 공식문서가 따로 있었어요! StrictMode에 대한 내용이 살짝 다르니 최신 버전 한번 확인해보세요😊

예은님이 보내주신 사이트의 설명에는 렌더링을 하지 않는다고 되어 있는데, 최신 공식 문서에는 추가로 다시 렌더링을 진행한다고 되어있네요!

2024-11-28 07:50 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +import {v4 as uuidv4} from "uuid";
3개를 걸어 놓으셨는데 아마도 `uuid`에 대해 물어보신 거겠죠??

의천님이 [코드 리뷰](https://github.com/cho-log/self-paced-react/pull/33#discussion_r1845286939)로 남겨주신 내용 중 id 값으로 `Date.now`를 쓰는 것도 좋지만 `uuid` 기능이 존재하니 도입하시는 것을 추천해주셨어요!

2024-11-28 07:51 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +        ${(props) => props.$isRequired &&
의천님이 남겨주신 [코드 리뷰](https://github.com/greedy-team/self-paced-react-advanced/pull/3#discussion_r1855191253) 내용 입니다! 저도 처음 배웠어요😊

2024-11-28 07:52 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +export const useRestaurantContext = () => useContext(RestaurantContext);
알고 사용한 것은 아니지만.. 이런 방식도 있더군요...

2024-11-28 08:13 UTC, gogo1414 commented
코드 리뷰를 반영하면서 아래의 내용을 작성해보도록 하겠습니다😊

## Context API를 왜 사용하는지

맨 위 상위 컴포넌트에서 `deapth` 가 매우 깊은 하위 컴포넌트로 `props` 를 전달하기 위해서 거쳐야하는 컴포넌트를 생각했을 경우 `props` 가 실질적으로 필요한 해당 컴포넌트를 제외하고는 나머지 거쳐가는 컴포넌트는 해당 정보를 `props`로 전달받다 보면 나중에 무수히 많은 `props`가 쌓여 있는 모습을 보고 가독성도 떨어지고 어디서 사용되는지 파악하기 위해 무수히 많은 컴포넌트 창을 켜야될 수도 있을 거라는 생각이 드네요.

위와 같은 문제점들을 해결하기 위해 Context API를 사용하는게 아닌가 싶어요!

## 기존의 코드구조와 어떤 trade-off가 있는지

기존의 코드 구조에서는 `props`를 전달하기 위해 중간에 props를 받아 경유 해야하는 컴포넌트가 존재했지만, 이제는 그럴 필요 없이 사용이 필요한 컴포넌트 내에서 useContext를 통해 RestaurantContext에 필요로 하는 정보를 따로 불러올 수 있어요!

다만 좀 아쉬운 점은 Context API가 모든 정보를 관리하게 될 경우 각 컴포넌트에서 직접 접근하지 않더라도 접근이 가능한 보안적인 문제는 존재한다고 생각해요. props를 완전히 분리해서 사용하는 것이 아니다 보니 이러한 생각이 드네요..

2024-11-29 14:15 UTC, ye6194 commented
안녕하세요 준수님!

잘못된 링크 첨부해서 죄송해요ㅠ 실수로 옛날 버전 링크를 걸었는데 제대로 된 링크를 잘 찾아서 보셨네요!!
라인은 분명히 한줄 걸었는데 왜 여러줄이 걸려있는지 모르겠네요🤔

새로 추가된 데이터 흐름도와 context API를 사용하는 이유, trade-off 잘 읽었습니다!
리뷰 답변 달고 코드 수정하시느라 수고하셨어요👍

2024-12-02 09:52 UTC, Indigochi1d requested changes
안녕하세요 준수님✋🏻 리뷰가 조금 늦어졌네요 ㅠ 시험공부는 잘 되어가시나요?

이번 미션은 ContextAPI로 상태를 전역에 관리해보는 것을 구현하는 미션이었습니다. 저희가 초록스터디 하면서 겪어왔던 `props drilling`  문제를 해결해보는 것이 주 목적이었는데요!  12/29 저번주 스터디에 `props drilling` 은 정말 나쁘기만 한 것인가? 에 대한 이야기도 나누어봤던 것을 기억하실 거에요. 

또 이전 스터디들 중에서 `컴포넌트의 책임`에 대해서 이야기를 나눈적이 있죠? 상태를 전역으로 만들어서 `Provider`안에 넣고 관리할 때, 전역상태의 선정기준은 여러가지가 있겠는데요. 제가 가장 중요하게 생각하고 애플리케이션을 설계하는 점은 두 가지입니다.
1. 컴포넌트의 책임의 수준
2. 경유하는 컴포넌트가 너무 많음(props drilling)
 
뭔가 당연한가요? 그렇다면 준수님이 여태까지 잘해오셨다는 증거입니다ㅎㅎ

### 1️⃣ 코드 리뷰
준수님의 코드를 보았을 때 조금 신기한 점이 있었어요. 코드 조각에 써 놓았던 리뷰처럼 Contexts에서 반환을 `useContext`를 입혀 반환하는 것이 이렇게 해도 될까? 라는 의문을 가지게 했습니다. 옳지 않은 코드는 아닌데 제가 자주 보던 ContextAPI 에서의 코드패턴이 아니라 신기했어요. 리뷰에 꼭 답변달아주세요 ㅎㅎ 
그 외로는 잘 작성해주셨는데요. 한가지 아쉬운 점은 Context에서 비즈니스 로직이 수행되고 있다는 점입니다. 해당 비즈니스 로직은 실제로 수행되는 컴포넌트에서 수행되어야 맞고 컴포넌트에서 수행되었을 때 전역으로 관리되던  **"상태"** 민   바꿔주면서 수행하는게 더 올바른 데이터흐름 같아요.(물론 이 프로젝트에선 state-props가 제일 좋은 데이터 흐름이지만요😆)

### 2️⃣ 호기심에 대한 답변

> 호기심이라기 보다 toggleModal 설정을 해제해서 다르게 적용해야할 지 고민했었어요 RestaurantProvider를 main.jsx 에 적용해서 그 문제는 피했지만(또 다른 적용 방법이 있긴 했겠죠..?) 기존 코드를 교체할 때가 왔나 싶었답니다..

이렇게 적어주셨네요! 혹시 어떤 상황인지 더 구체적으로 작성해주시면 도움을 드릴 수 있을 것 같아요. 필요하다면 페어프로그래밍도 가능하니 꼭 말해주세용


이번 주차도 수고하셨어요! 시험 준비 잘하시고 종강하고 27일에 뵙도록 하겠습니다! 참고로 ContextAPI가 아직도 아리까리하다면 [저희 8주차 스터디 링크](https://www.notion.so/sejong-greedy/8-f7c485e320d94e7d9b0f0872cbd8d4cc?pvs=4)
를 달아놓을테니 스터디 시간에 본 PPT를 보고 제 코드를 보신 후 올려드린 자료인 [더북](https://thebook.io/080203/0501/) 을 다시 한번 본다면 완벽한 이해가 될거에요! 

수고하셨습니다💯

2024-12-06 07:38 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +    };
생각해보니 비즈니스 로직이네요!! 상태관리를 위한 것들과 로직의 분리가 필요해보이네요...

2024-12-06 09:24 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +    };
궁금한 점이 리액트에서 의미하는 비즈니스 로직이 UI로직도 포함되나요? 토글 모달의 경우 비즈니스 로직이 아니라 UI 로직으로 생각이 들어서요!

2024-12-06 10:40 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +export const useRestaurantContext = () => useContext(RestaurantContext);
흠... 딱히 의도는 없었어요... 리액트 네이밍 자체를 잘 몰라서 다만, 사용할 때 use를 앞에 붙이길래 사용했습니다(?)

2024-12-06 10:40 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +        >
넵 시험기간 끝나고 진행해보도록 하겠습니다...!

2024-12-06 10:41 UTC, gogo1414 commented on src/contexts/RestaurantContext.jsx
> +    };
분리를 해보려고 했는데 잘 안되네요ㅠ 아마 레스토랑 정보를 커스텀 훅으로 관리하다보니
`addRestaurant()`를 모달에서 적용하려고 하니 추가된 레스토랑 정보가 바로 안나오는 문제가 생겼는데(새로 고침 하면 나옵니다ㅎㅎ...), 렌더링이 먼저 되는게 원인인지 아니면 상태 변경을 아예 눈치채지 못한 것인지를 모르겠네요..!

2024-12-07 04:15 UTC, Indigochi1d commented
@gogo1414 우선 미션 머지기한이 다 되어 머지해놓고 이번 미션은 넘어갈게요! 다음 recoil미션때 재구성하시면서 리팩토링 거치시면 좋을 것 같아요! 수고하셨습니다!

2024-12-07 04:15 UTC, merged