Adv 2 1
greedy-team/self-paced-react-advanced pull request #6
Opened 2024-11-26 14:53 UTC by Songhyejeong

안녕하세요 리뷰어님! 

평소 상태 관리를 비교적 간편한 zustand를 써서, context API는 처음인데요! 
비슷하면서 굉장히 다른 느낌을 받았습니다. zustand가 확실히 간단한 것 같습니다.
사실 Modal에 처음 Context를 적용하고 나서 뭔가 잘못된거 같은? 코드가 복잡해지는 느낌을 받았는데요.
알고보니 제가  https://thebook.io/080203/0528/
이 사이트를 참고해서 하다가, useContext를 사용하지 않는 방식을 택했더라고요. 그리고 이 방식은 옛날 방식이라서 복잡한 방식이고 추천하지 않는 방식이라는걸 깨달았습니다..  

리팩토링 하면서 useContext도 사용해보고자 합니다!

##  구현 사항
- Context API를 사용해서 애플리케이션 내의 **props drilling** 문제를 해결한다.
  - props로 **똑같은** 데이터 혹은 함수를 전달하지 않도록 해야한다.

###  Context API 와 기존 코드의 trade-off
기존코드는 props를 전하는 깊이가 깊어져 props drilling 문제가 발생한다. props가 필요하지 않는 컴포넌트까지 전달하게 된다. props가 바뀌면 불필요한 렌더링이 생긴다. 또한 코드를 리팩터링하고 유지보수 하기 어려운 단점이 있다. 

Context API는 상태를 해당 컴포넌트로 바로 사용할 수 있게 전달해주며 이는 props drilling 문제를 해결하며 
props의 깊이가 길어지는 것을 방지한다. 하지만 Context API를 무지성으로 사용하면 컴포넌트 간의 의존성이 높아지는 문제가 있다. 

### props 사용한 이유
저는 props의 전달하는 깊이가 1인 props는 Context API를 적용할 필요가 없다고 생각하여 props로 값을 넘겨주었습니다.

### 컴포넌트 구조 (Context API와 컴포넌트의 관계)

<img width="500" alt="Screenshot 2024-11-26 at 11 35 57 PM" src="https://github.com/user-attachments/assets/59e026cd-a2ba-49a9-96d2-01fed88cc447">

### 실행 영상 
https://github.com/user-attachments/assets/f5cbd3c3-4e27-407d-8509-dbf32574006a

2024-11-29 17:00 UTC, Songhyejeong reviewed
안녕하세요 준수님 ! 리뷰 감사합니다~ !
얼른 리팩터링 진행 해야겠어요~ 
> 코드 보면서 전반적으로 느낀건 각 컴포넌트에 맞게 Context를 분리하려고 한 점이 인상 깊었어요👍 저는 한 곳에서 관리를 진행하려고 했는데, 별도로 분리하면 더 좋겠네요!

맞아요! 전역 상태도 상태마다 역할이 다르고 무엇보다 아까 스터디에서 범수님이 말씀해주셨던 것 처럼 불필요하게 리렌더링 되는 문제를 막을 수 있어서 좋은 것 같습니다! 👍 

> 오 저는 다 Context API로 진행했어요! 그때 적용하는 걸 목적으로 사용해보라고 하셨었는데 까먹으셨나봅니다!

맞아요 ! 저도 하면서 전부 적용 하라고 하셨는데 하다가 사실

```
<>
   <CategoryFilter
       category={category}
       onChangeCategory={setCategory}
      />
     <RestaurantList restaurants={filteredRestaurants} />
 </>
```
여기서 filteredRestaurants를 어떻게 useContext에서 정의하고 사용할지 감이 안와서.. 나뒀답니다
filteredRestaurants를 정의하려면 category도 있어야하고.. restaurants도 있어야하고..
useContext 훅을 쓰면 달라질지도 모르겠네요,,

2024-11-29 17:00 UTC, Songhyejeong commented on src/components/main/categoryFilter/CategoryFilter.jsx
> +  & > select {
`>`는 자식 요소를 의미합니다 
`&` 가 현재 선택자를 가리키므로 `& > select`는 `RestaurantFilterContainer`의 자식요소인 select에 스타일을 입히는 거라고 할 수 있습니다 !

2024-11-29 17:00 UTC, Songhyejeong commented on src/components/aside/Aside.jsx
> +    </ModalConsumer>
제가 조금 다른 방식을 사용해서.. 저도 처음에는 이해 하는데 오래걸렸답니다
```
const ModalProvider = ({ children }) => {
  const [detailModal, setDetailModal] = useState(false);
  const [addModal, setAddModal] = useState(false);

  const value = {
    state: { detailModal, addModal },
    actions: { setDetailModal, setAddModal },
  };

  return (
    <ModalContext.Provider value={value}>{children}</ModalContext.Provider>
  );
};
```
1. `ModalContext`의 코드인데 현재 ModalProvider에서 `detailModal`과 `addModal`의 상태를 관리하고 있습니다.

2. `Aside`컴포넌트의 의`<ModalConsumer> </ModalConsumer>`로 감싸진 컴포넌트는 `ModalProvider`의 state와 actions 를 사용할 수 있는, 다르게 말하면 value를 구독하여 이 값을 가져오는 컴포넌트 입니다. 여기서는 state의 `detailModal`, `addModal`값을 가져오고 있습니다 !

3. ` { state: { detailModal, addModal } }`value에서 state 객체를 구조 분해 할당으로 가져옵니다. 그리고 detailModal, addModal 값을 기준으로 조건부 렌더링을 수행합니다.

2024-11-29 17:00 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
> +  const [description, setDescription] = useState('');
이 값들은 모달창 내에서 Form을 작성하는 값들입니다!
모달창 내에서 값들이 바뀌기도 하고, API의 body로 보내지는 값들이기 때문에, 모달 창에 의존한다고 생각해서 모달창 내에서 상태관리를 하는 코드로 작성해봤습니다! 🙂

2024-12-02 14:47 UTC, wzrabbit requested changes
@Songhyejeong 👋🏻 

드디어 state-props를 사용해 데이터를 전달하는 방법 외에 새로운 방법을 써 보는 첫 번째 미션이군요. Zustand를 사용하셨다고 하던데 React에서 자체 제공하는 API를 사용해 전역 상태들을 관리해보신 소감은 어떠신가요 👀 

> 평소 상태 관리를 비교적 간편한 zustand를 써서, context API는 처음인데요!

저는 Zustand를 사용한 경험이 없습니다. Zustand는 Context API와 비교했을 때 어떤 편리한 점이 있을까요? 어떤 방식으로 구현하는지도 궁금하네요 👀 아 물론, 이건 이번 미션 주제는 아니니 만약 공유해주시고 싶다면 Discord같은 곳에 간단하게나마 공유해 주시면 감사하겠습니다. 필수는 아니니까 부담 가지시지 않아도 돼요

저도 Zustand 이후에 입문해 보고 싶네요

> 이 사이트를 참고해서 하다가, useContext를 사용하지 않는 방식을 택했더라고요. 그리고 이 방식은 옛날 방식이라서 복잡한 방식이고 추천하지 않는 방식이라는걸 깨달았습니다.

네, 지금은 `useContext` hook이 광범위하게 사용되고 있고, 이쪽이 구현하시기에도 더 간편하셨을 거에요. 이 hook이 지금은 사용 사례가 훨씬 더 많습니다. 나중에 시간이 되시면 구현이 편한 것 외에도 어떤 점이 기존 방식과 비교했을 때 얻어갈 수 있는 장점이 있는지 알아보셔도 좋을 것 같아요

> 저는 props의 전달하는 깊이가 1인 props는 Context API를 적용할 필요가 없다고 생각하여 props로 값을 넘겨주었습니다.

**정말 잘하셨습니다.**

아마 메인테이너님께서 모든 곳에 Context API를 사용해 보시라고 미션을 주셨던 것 같아요. 그런데 이후 스터디에서 다시 모였을 때는 메인테이너님께서 "정말 모든 곳에 Context API를 적용하는 게 맞을까" 라는 주제로 이야기하신 것으로 알고 있어요. 요구사항은 의도된 요구사항이었습니다.

미션의 요구사항은 어기셨지만, 언제 Context API를 적용해야 할지 검색을 어느 정도 해보셨다면 **모든 곳에 무조건 적용하지 않고, 필요한 부분에 한하여 적용하는 것이 좋을 것이라는** 의견이 많았을 것이고, 이를 판단해 나름대로의 기준을 가지고 적용해 주신 것 같아요.

(메인테이너님은 싫어하실 수도 있겠지만 😈 ) 앞으로 납득되지 않는 요구사항이 있다면, 그리고 따르지 않을 충분한 이유가 보인다면, **한 번 요구사항 어겨보세요.**
이곳은 "왜?" 를 중요시하는 토론의 장입니다. 왜 요구사항을 따르지 않았냐고 물으신다면 자신있게 스터디원, 메인테이너님과 의견을 나눠보세요. 저는 그것도 좋은 학습법이라고 생각해요.

물론 메인테이너님이 정해주신 커리큘럼은 어기지 않는 면에서요. Recoil 사용이 요구사항인데 좋아하는 Zustand 쓰시면 그건 안 됩니다 ㅎㅎ...

## 1️⃣ 리뷰
- 기존 방식에서 `useContext` hook을 사용하는 형식으로 리팩터링하신 것 확인했고요, 깔끔하게 잘 적용해 주신 것 같습니다. 이번 미션에서 Context API 구현사항과 관련해서 저는 별다르게 드릴 코멘트는 없었습니다. 지금 구성은 정말 깔끔해요. 👍🏻 
- 레스토랑 추가 모달 컴포넌트에서는 UI/UX 면에서 아쉬움이 느껴졌어요. 사용자에게 보여지는 UI와 실제 동작이 다르다는 것을 느꼈고, 잘못된 값을 입력했을 때 모달이 닫혀 작업 내역이 손실되는 점은 사용자 입장에서 불편한 UX를 느끼게 되는 원인이 되었던 것 같아요. 관련 내용은 코멘트로 달아두었으니 참고 및 의견 공유를 부탁드리겠습니다.

## 2️⃣ Context API 도입에 관한 고민

구현하시는 방법은 이미 잘 터득하신 것 같아보여요. 그렇다면 이후 (꼭 반영하지는 않더라도) 어떤 상황에서 Context API의 도입이 필요할 지, 어떨 때는 도입하는 것이 오히려 악수일 지 고민해 보시면 좋을 것 같습니다. 

사실 이게 정말 중요한 고민인 게 Context API가 꼭 아니더라도 다른 상태 관련 라이브러리들도 전역 상태를 다루는 것과 관련이 있기 때문에 비슷한 장점과 단점을 공유하거든요. 앞으로도 쭉 컴포넌트를 설계하시면서 이러한 고민은 계속될 거에요.

약소하지만 제가 생각하는 의견도 여기 적어볼게요. 이게 정답이라는 것이 아니라 **제가 개인적으로 생각하는 의견** 일 뿐이니 **하나의 의견** 으로써 활용하시면 좋을 것 같습니다.

### ⭐ 재사용이 절실한 컴포넌트에는 Context API를 도입할 때 신중을 가하자
저는 컴포넌트를 크게 두 부류로 나눠서 생각해요.
- "재사용에 용이하도록 구현된 컴포넌트"
- "재사용이 제한되지만, 특정한 도메인의 기능을 수행하도록 구현된 컴포넌트"

전자의 경우에는 저는 Context API를 도입할 때 굉장히 신중하게 생각해요. 왜냐하면 이 컴포넌트들은 한 종류의 기능에 종속되는 컴포넌트가 아닌, 여러 종류의 컴포넌트를 부모 컴포넌트로 둘 수 있는, 만능 컴포넌트이거든요. 이 컴포넌트의 예시를 들자면 레스토랑 추가 모달의 버튼 컴포넌트를 예로 들 수 있어요. 버튼 컴포넌트 자체는 특정 기능에 종속되기보다는 어느 컴포넌트가 부모 컴포넌트가 되느냐에 따라 무궁무진한 범용성을 발휘할 수 있거든요.

Context API를 도입한다는 것은 그 컴포넌트가 특정 도메인과 소통하고, **그 도메인에 한정되는 일을 하도록 제한함** 을 의미해요. 이 경우에는 이러한 컴포넌트를 다른 용도로 사용하고 싶어도 그러기 힘들 거에요.

### ⭐ props drilling을 고려하되, props drilling으로만 판단하지 말자
React 공식 문서에서는 아래와 같이 적혀있어요.
> Context is very tempting to use! However, this also means it’s too easy to overuse it. Just because you need to pass some props several levels deep doesn’t mean you should put that information into context.

> Context API는 사용하기 굉장히 유혹적입니다! 하지만, 이는 남용하기 쉽다는 것을 의미하기도 합니다. 여러 계층에 걸쳐 props를 통과시켜야 한다는 점 자체가 Context API를 사용해야 하는 것을 의미하지는 않습니다.

props drilling이 다소 심하더라도, 계층에 속하는 컴포넌트들이 그 props와 연관성이 깊고 use-case로도 적합하다면 props drilling으로 데이터를 내리도록 두는 것은 나쁘지 않다고 생각해요. 자연스러운 데이터 흐름이라고 생각합니다.

반대로 계층의 깊이가 깊지 않더라도 use-case로 적합하지 않은 사례이고 이 Context가 여러 계층에 걸쳐서, 여러 컴포넌트에서 광범위하게 쓰인다면 이 변수를 props로 통과시키는 방법을 사용하는 것은 굉장히 고통스럽고 유지보수도 어렵게 하겠죠. 저는 이 때가 Context API를 사용하기 정말 좋은 상황이라고 생각해요.

### ⭐구조가 복잡하다면 재사용이 가능한 컴포넌트 단계에서는 props drilling을, 특정 기능을 담당하는 컴포넌트 단계에서는 Context API를 사용해 관리해보자

상황에 따라 다르겠지만, 저는 이 방식으로 개발하는 것을 좋아하는 것 같아요. 

공용 인풋 컴포넌트, 공용 버튼 컴포넌트 등과 같이 광범위하게 쓰일 수 있는 컴포넌트를 조합시킬 때는 props drilling으로 데이터를 전달시키고, 계층을 올라가다가 재사용이 제한되지만 특정 기능을 담당하는 컴포넌트 계층에 왔다면, 여기서부터는 Context API 등을 사용해 전역으로 소통하는 거에요.

### ⭐하나의 Context를 여러 컴포넌트가 사용하는데, 극히 일부분의 값만을 사용한다면 Context를 여러 개로 분리하는 것을 고려해보자

Context API를 **구독** 하는 컴포넌트들은 기본적으로 전역에 위치한 데이터의 값이 변경되면 리렌더링 됩니다. 여기서 하나의 Context를 사용하는 여러 컴포넌트들이 있는데, 각 컴포넌트가 Context의 극히 일부를 사용한다면 어떻게 될까요? 예를 들어,

```js
const myData = {
  a: 1,
  b: 2,
  c: 3,
  d: 4
};
```

이와 같은 데이터가 있는데, 컴포넌트 A는 `a`만, 컴포넌트 B는 `b`만, ... 과 같이 컴포넌트가 아주 일부분의 값만 사용한다면요?

`a`가 나중에 변경되었을 때, 컴포넌트 A는 리렌더링되는 것이 적합하지만, `a`를 사용하지 않지만 해당 Context를 구독하는 수많은 컴포넌트들은 렌더링될 필요가 없음에도 리렌더링이 될 거에요. 즉, 각 컴포넌트가 컴포넌트를 너무 일부분만 사용하는 경우라면 불필요한 리렌더링이 많이 발생할 수 있고, 이게 심해지면 성능에도 영향을 줄 수 있을 거에요.

그래서, 이러한 문제가 발생한다면 저는 Context를 분리해보는 방법을 고려해보기도 해요.

![image](https://github.com/user-attachments/assets/c495f0dd-db9e-4d44-9bc0-3e0e07ff210b)

지금 떠오르는 의견은 이 정도네요 😄 그럼, 혜정님의 의견 기다리겠습니다!

2024-12-02 14:47 UTC, wzrabbit commented on src/components/aside/AddRestaurantModal.jsx
이전 리뷰에서는 제가 미처 눈치채지 못했었는데요 😢 
75번째 줄, 94번째 줄에 `<StyledLabel>` 에 `required` attribute가 달려있더라고요. 그런데, `required`는 `<label>` 태그에는 달 수 없는 속성이고, 실제로 아무 영향을 주지 못할 거에요

현재 `<AddRestaurantModal>` 에서 저는 아래의 세 가지 개선점이 보여요

1. "이름" 필드에 아무것도 입력하지 않더라도 폼 자체의 로직은 통과해 지정해둔 alert 메시지 "이름을 입력해주세요" 가 뜨는 상황이에요. 폼에서 아예 막혔다면 "이름을 입력해주세요" alert 메시지는 보이지 않았을 것으로 예상해요.
2. "설명" 필드에 아무것도 입력하지 않은 경우에도 폼 로직이 통과해야 하는데, alert 메시지가 보이면서 폼 제출을 막고 있어요.
3. 사용자가 폼을 잘못 입력한 상황에서 alert 메시지가 보인 후 사용자가 alert 메시지를 닫았을 때, 모달이 그대로 유지되지 않고 닫히더라고요. 사용자가 입력한 사항이 손실되지 않도록 사용자가 잘못 입력한 경우에는 모달이 닫히지 않도록 리팩터링 해 보시는 것은 어떨까요?

구현 시에는 두 가지를 고민해 주시면 좋을 것 같아요:

1. `required` 는 어느 태그에 달려야 효력을 발휘할까요?
4. `<StyledLabel>` 에서 `required` attribute를 사용하지 않으면서, 여전히 필수값임을 나타내는 별표를 props에 따라 개발자가 조절할 수 있으려면 어떻게 해야 할까요?

2024-12-02 14:47 UTC, wzrabbit commented on src/context/SelectedRestaurantContext.jsx
> +export { SelectedRestaurantProvider, SelectedRestaurantContext };
Context API를 사용하기 위한 깔끔한 구성이네요 👍🏻 Consumer를 사용하셨다고 들었어요, 리팩터링하시느라 고생 많으셨어요

이름 및 사용 범위에서도 의도가 잘 드러나는 것 같아요

2024-12-05 09:02 UTC, Songhyejeong commented
@wzrabbit 의천님 안녕하세요! 이번에도 유익한 리뷰 감사합니다! 
의천님이 공유해주신 내용 읽어보고 답변 몇개와 질문 남겨보았습니다. 😄 

> 드디어 state-props를 사용해 데이터를 전달하는 방법 외에 새로운 방법을 써 보는 첫 번째 미션이군요. Zustand를 사용하셨다고 하던데 React에서 자체 제공하는 API를 사용해 전역 상태들을 관리해보신 소감은 어떠신가요 👀


Zustand를 사용했을 때는 사실 `Provider`, `Cunsumer` 라는 개념이 없었고 `store`라는 state관리 저장소로 바로 상태를 만들고 관리할 수 있었거든요. 그리고 Zustand는 localStorage에 상태를 저장해주는 기능이 있어서 전역으로 상태를 관리하고 추적하기 편했던 것 같아요!
`React`에서 자체 제공하는 API를 사용해보니, 처음 제가 사용했었던 옛날 방식에서 `Provider`와 `Consumer`를 정의하고 적용하는 과정에서 이 **둘의 관계를 더 명확**하게 이해하게 되었던 거 같아요. 이 둘의 차이에 대해서도 한 번 정리하고 공유해보면 좋을 것 같네요!

>앞으로 납득되지 않는 요구사항이 있다면, 그리고 따르지 않을 충분한 이유가 보인다면, 한 번 요구사항 어겨보세요.
이곳은 "왜?" 를 중요시하는 토론의 장입니다. 왜 요구사항을 따르지 않았냐고 물으신다면 자신있게 스터디원, 메인테이너님과 의견을 나눠보세요. 저는 그것도 좋은 학습법이라고 생각해요.

좋습니다. 저도 사실 이렇게 코드 리뷰 하는 환경이 의미 있다고 생각해요..! 흔하게 할 수 있는 것도 아니고요 잘 활용해봐야겠네요!

>2️⃣ Context API 도입에 관한 고민

Context API 도입은 스터디 시간에도 중요하게 다뤘었고 Context API뿐 아니라, 다른 전역 상태 관리를 도입할 때도 그 기준을 나누는게 항상 어려워서 고민이었는데 누군가의 의견을 듣는 거는 처음이라서 뜻깊었습니다! 


>⭐ 재사용이 절실한 컴포넌트에는 Context API를 도입할 때 신중을 가하자
 
오 **Context API가 도메인이 한정된 일을 하도록 제한한다**라는 개념은 처음 생각해보는 거 같아요! 그 이유가 특정 `state`와 `actions`을 미리 정의하는 특성 때문이라고 생각하면 될까요? 이 특성을 생각하면 Context API의 도입에서 재사용 컴포넌트인지가 그 기준이 될 수 도 있겠군요~!
그러면 반대로 props로 내려주는 것은 props 속성값만 전달하고, 상태 변경은 하위 컴포넌트에서 자유롭게 바꿀 수 있으니 의천님이 말씀하신대로 무궁무진한 범용성을 가진다. 라고 생각하면 되겠네요!


### 궁금한 점

의천님의 리뷰를 읽어보고 한 가지 궁금한 점이 생겼습니다! 의천님이 공유해주신 아래 사진에서는 상태가 자주 바뀌는 경우 Context API를 사용하는 것이 좋지 않다고 언급되어 있는데, 그 이유는 리렌더링이 자주 발생해서 성능에 문제가 생길 수 있기 때문이라고 나와있네요. 
이런 경우 전역 상태로 관리하면 성능 측면에서 많이 안 좋을까요? 
상태가 자주 바뀌고 그 상태를 공유하는 컴포넌트들이 많을 경우, 현재 상태를 추적하기 어려워지는 상황이 발생할 수 있더라고요. 이런 경우에는 전역 상태로 관리하는 것이 효율적일 것 같아서 전역으로 관리 했던 경험이 있어서 궁금해졌습니다..! 

![image](https://github.com/user-attachments/assets/5442addf-988e-46d2-ac30-2bf94a46b901)

감사합니다..!🙃

2024-12-05 09:28 UTC, Songhyejeong commented on src/context/ModalContext.jsx
> +export { ModalProvider, ModalContext };
## 답변 

1. 제 생각에는 의천님이 말씀해주신 의견을 빌려 말하자면 모달은 재사용에 용이한 컴포넌트이지만, 열고 닫는 상태로 기능이 특정 되어 있어서 Context API에 적합한 것 같습니다. 그리고 이 부분은 스터디 시간에도 범수님께서 공유해주신 내용인데 다음 사진과 같이 이 전 미션들에서 modal을 props로 정말 많이 넘겨주었는데 Context API로 관리하니 정말 편하더라고요! 
또한 굳이 모달의 상태를 알지 않아도 되는 컴포넌트까지 모달의 상태가 전달되고 또 전달되면서 리렌더링 되니, 성능 문제에서도 좋지 않았을 것이라고 생각이 드네요!
![image](https://github.com/user-attachments/assets/5e361534-dda1-409b-b862-303c55910408)

3. 음,,, 30 종류의 모달이라면.... 우선 많은 리렌더링을 막기위해 하나의 Context에서 관리하는 것보다는 분리 할 것 같은데 그러면 30개의 Context가 생기는 건 너무 코드의 크기가 커질까 고민이네요🤔 조금 더 고민해봐야할 거 같아요

2024-12-05 09:29 UTC, Songhyejeong commented on src/components/aside/Aside.jsx
> +      {addModal && <AddRestaurantModal />}
지금 보니 정확히 어떤 동작을하는지 알아보기 어렵겠네요! 열린다는 동작을 의미하는 네이밍으로 변경하는게 좋겠네요

2024-12-05 09:43 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
Context API 적용 하면서, 폼의 작동 기능을 정확하게 테스트 하지 못했던 거 같습니다..! 
 required 속성을 label 태그에 줄 수 없겠네요..
그렇다면 지난주 리뷰 때 의천님께서 언급해주신 방법을 사용하거나 아니면 styled-component에서 자식 선택자를 참고하여 별표 속성을 줄지 않줄지 판별하는 방법도 가능 할 것 같은데, 이 방법은 되는지 확신이 들지는 않네요..

2024-12-06 12:51 UTC, wzrabbit commented on src/context/ModalContext.jsx
> +export { ModalProvider, ModalContext };
## 1️⃣

 문제에 대해 나름대로의 고민을 해보셨군요. 

> 모달의 상태를 알지 않아도 되는 컴포넌트까지 모달의 상태가 전달되고 

말씀하신 부분이 챙길 수 있는 핵심적인 좋은 장점을 챙겨가는 데 동기가 되는 특징일 거에요. 모달을 한두곳에서 사용한다면 사실 괜찮을 수 있어요. 문제는 **모달은 보통 프로젝트에서 내버려두질 않아요. 너무나 많은 컴포넌트가 모달을 사용합니다.** 『여러 계층에서 광범위하게 사용되다 보니』 한 곳의 도메인을 담당하는 기능으로 두기도 어려운 상황이 많은 것 같습니다. 그때마다 props로 모달을 건드리는 로직이 들어온다면 관리도 불편해지고 컴포넌트 본연의 기능에 초점을 맞춘 props를 두기도 어려울 거라 생각해요.

## 2️⃣ 

Context API와 관련된 질문이기도 하지만 단순히 state를 어떻게 다루면 좋을지, 어떻게 하면 유지보수에 힘든 노가다를 하지 않고도 여러 종류의 모달을 관리할 수 있도록 데이터의 형식을 개선해 볼 수 있을지를 고민해 보시면 어떨까요?

약간 힌트를 흘리자면, `is~~~` 네이밍을 사용한 `boolean` 변수는 두 가지의 상태만을 나타낼 수 있겠죠: "그 모달이 열려 있든가", "그 모달이 닫혀있든가". 다른 자료형을 사용한다면 더 많은 상황을 나타낼 수 있지 않을까요?

지금은 고민해보고 싶으신 것 같아 답변은 드리지 않겠습니다. 최선의 답안은 아니겠지만 제 이야기를 들어보고 싶으시다면 커뮤니티 내에서 언제든지 멘션해주세요.

2024-12-06 13:49 UTC, wzrabbit approved these changes
@Songhyejeong 여러 코멘트들 반영하시느라 수고 많으셨어요. 코멘트를 꼼꼼하게 읽으시고 그에 맞춰 해결 방법을 고려하시는 게 잘 느껴지네요. 👍🏻 

## 1️⃣ 질문/답변

> Zustand를 사용했을 때는 사실 Provider, Cunsumer 라는 개념이 없었고 store라는 state관리 저장소로 바로 상태를 만들고 관리할 수 있었거든요. 그리고 Zustand는 localStorage에 상태를 저장해주는 기능이 있어서 전역으로 상태를 관리하고 추적하기 편했던 것 같아요!
React에서 자체 제공하는 API를 사용해보니, 처음 제가 사용했었던 옛날 방식에서 Provider와 Consumer를 정의하고 적용하는 과정에서 이 둘의 관계를 더 명확하게 이해하게 되었던 거 같아요. 이 둘의 차이에 대해서도 한 번 정리하고 공유해보면 좋을 것 같네요!

아예 `store`라는 개념을 두는군요. 매번 `<Provider>` 쓰는 게 귀찮은 걸 생각하면 코드를 깔끔하게 가져갈 수 있는 방향이라고도 생각되지만, 지금으로써는 사용한 경험이 없어 잘은 모르겠네요.

`localStorage` 에 저장하는 건 상당히 신박하네요 `localStorage`에 무언가를 저장해야 하는 일이 은근 있었거든요

> 특정 state와 actions을 미리 정의하는 특성 때문이라고 생각하면 될까요? 이 특성을 생각하면 Context API의 도입에서 재사용 컴포넌트인지가 그 기준이 될 수 도 있겠군요~!
그러면 반대로 props로 내려주는 것은 props 속성값만 전달하고, 상태 변경은 하위 컴포넌트에서 자유롭게 바꿀 수 있으니 의천님이 말씀하신대로 무궁무진한 범용성을 가진다. 라고 생각하면 되겠네요!

네, 정확합니다. Context API를 구독하는 컴포넌트는 호출하는 함수가 **자연스레 정해지게 됩니다.** 그러니까 특정 도메인을 수행하기 위한 사용처로써 제한되는 것이죠. 반면 재사용이 되도독 의도된 컴포넌트는 부모가 무엇이든 `props`로 오는 함수를 실행하므로 어느 컴포넌트가 부모 컴포넌트로 오느냐에 따라 **사용처를 자유롭게 정할 수 있습니다.** 여담으로 이러한 재사용에 용이한 컴포넌트들은 네이밍, 기능 면에서 특정 도메인과 연관되는 무언가를 하기보다는 자신의 범용적인 기능에만 충실한 경우가 많습니다. 예를 들어 버튼 컴포넌트라면 "자신이 클릭될 경우 props로 전달된 `onClick` 콜백 함수를 실행한다." 와 같이요. 특정 도메인의 기능을 수행한다기보다는 구체적으로 무엇을 할지는 도메인을 결정짓는 입장인 부모에게 맡기고 있죠?

이 특징을 잘 활용해주신다면 Context API의 똑똑한 사용은 물론 각 컴포넌트의 의도 및 설계를 하는 데도 도움이 될 것이라 생각합니다.

> 의천님의 리뷰를 읽어보고 한 가지 궁금한 점이 생겼습니다! 의천님이 공유해주신 아래 사진에서는 상태가 자주 바뀌는 경우 Context API를 사용하는 것이 좋지 않다고 언급되어 있는데, 그 이유는 리렌더링이 자주 발생해서 성능에 문제가 생길 수 있기 때문이라고 나와있네요.
이런 경우 전역 상태로 관리하면 성능 측면에서 많이 안 좋을까요?
상태가 자주 바뀌고 그 상태를 공유하는 컴포넌트들이 많을 경우, 현재 상태를 추적하기 어려워지는 상황이 발생할 수 있더라고요. 이런 경우에는 전역 상태로 관리하는 것이 효율적일 것 같아서 전역으로 관리 했던 경험이 있어서 궁금해졌습니다..!

답변을 한 문장으로 요약하면 **"빈번하게 리렌더링이 되야 할 이유가 충분한 컴포넌트들만 리렌더링이 되어야 하지 않을까요?"** 입니다.

첨부해 드린 자료의 경우에는 이 질문 분기를 먼저 지나치게 됩니다.
> Do consumers often only need **parts of the state** ?
> 본 context value를 사용하는 컴포넌트들이 state의 **일부분만을 사용**하고 있나요?

리렌더링이 빈번하게 일어나는 상황에서 Context API를 사용하는 것 그 자체가 나쁜 것은 아니라고 생각합니다. 문제는 **일부분만을 사용처가 사용한다** 에 있습니다. 일부분만을 사용한다는 것은 사용하지 않는 나머지 부분은 **다른 컴포넌트에게만 필요한 state들을 이 컴포넌트도 구독한다** 는 것을 의미하며, 이는 **리렌더링을 할 필요가 없는 상황임에도 다른 state가 바뀌어 리렌더링하게 됨** 을 의미합니다.

빈번하게 리렌더링되는 state들이 있는데 이를 구독하는 컴포넌트 중 그 빈번하게 리렌더링되는 state를 사용하지 않는다는 것은 그럴 필요가 없음에도 불구하고 빈번하게 리렌더링이 된다는 것을 의미하며, **필요하지 않은 성능 비용** 을 지불해야 한다는 것을 의미합니다. 따라서 대체로 좋은 상황이 아니라고 생각합니다. 이렇게 말씀드리면 이제 자료가 이해가 가실까요?

## 2️⃣ 반영 이후 새롭게 발생한 버그
- 코멘트 중 하나에 달아두었는데 애플리케이션에서 폼 제출 시 새로고침되는 버그가 존재하는 것 같습니다! 다음 미션에서 꼭 해결을 부탁드리겠습니다. ✏️

그럼, 저는 이만 물러나겠습니다! 열심히 리뷰 반영 하시느라 고생 많으셨어요 😄

2024-12-06 13:49 UTC, wzrabbit commented on src/components/aside/AddRestaurantModal.jsx
`shouldForwardProp` 을 이용해 처리해주셨군요. 잘 작동하는 것도 확인했답니다. 수고하셨어요.

2024-12-06 13:49 UTC, wzrabbit commented on src/components/aside/AddRestaurantModal.jsx
>      }
⚠️ 아쉽게도 현재 폼을 제출할 때 **새로고침**이 되는 문제가 발생하고 있습니다!  이는 `<button type="submit" />`의 기본 동작이 요인임을 알고 계실 것이라고 생각해요.

- 어떨 때 기본 동작이 수행되어야 할 지
- 지금 우리의 어플리케이션에서 기본 동작이 수행되는 것이 의도되는 동작일 지 고민해 보시면 좋을 것 같습니다.

이 문제에 대해서는 제가 해결 방법을 적어둔 적이 있으니 고민해 보신 이후에도 문제가 풀리지 않는다면 공유해드리도록 하겠습니다.

2024-12-06 13:49 UTC, wzrabbit commented on src/components/main/restaurant/RestaurantCard.jsx
버튼 컴포넌트에 한 번 마우스를 올려보실래요? 마우스 포인터가 바뀌죠? 이를 클릭 가능한 다른 콘텐츠에도 도입하면 `<RestaurantCard>` 또한 클릭할 수 있는 콘텐츠라는 것을 사용자에게 더 명확하게 알릴 수 있을 것이라고 생각해요.

`<RestaurantCard>` 에 마우스를 올리면 포인터가 바뀌도록 해 보는 것은 어떻게 생각하시나요?

2024-12-06 14:54 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
>      }
넵! 고민해보고 이후 미션에서 반영해보도록 하겠습니다..!

2024-12-06 14:55 UTC, Songhyejeong commented on src/components/main/restaurant/RestaurantCard.jsx
좋은 것 같습니다! 사용자가 `RestaurantCard`에 마우스를 올렸을 때는 포인터가 바뀌지 않는다면 클릭을 하는 콘텐츠인지 헷갈릴 수도 있겠네요..!

2024-12-06 14:56 UTC, Songhyejeong commented
@wzrabbit 안녕하세요 의천님 리뷰 답변 감사합니다 ! 완벽하게 고치지 못한 것들은 다음 미션에서 반영해보도록 하겠습니다 👍 

>네, 정확합니다. Context API를 구독하는 컴포넌트는 호출하는 함수가 자연스레 정해지게 됩니다. 그러니까 특정 도메인을 수행하기 위한 사용처로써 제한되는 것이죠. 반면 재사용이 되도독 의도된 컴포넌트는 부모가 무엇이든 props로 오는 함수를 실행하므로 어느 컴포넌트가 부모 컴포넌트로 오느냐에 따라 사용처를 자유롭게 정할 수 있습니다. 여담으로 이러한 재사용에 용이한 컴포넌트들은 네이밍, 기능 면에서 특정 도메인과 연관되는 무언가를 하기보다는 자신의 범용적인 기능에만 충실한 경우가 많습니다. 예를 들어 버튼 컴포넌트라면 "자신이 클릭될 경우 props로 전달된 onClick 콜백 함수를 실행한다." 와 같이요. 특정 도메인의 기능을 수행한다기보다는 구체적으로 무엇을 할지는 도메인을 결정짓는 입장인 부모에게 맡기고 있죠?
이 특징을 잘 활용해주신다면 Context API의 똑똑한 사용은 물론 각 컴포넌트의 의도 및 설계를 하는 데도 도움이 될 것이라 생각합니다.

넵 말씀해주신 Context API의 특징을 잘 살려서 컴포넌트를 잘 설계해봐야겠어요 !

> 답변을 한 문장으로 요약하면 "빈번하게 리렌더링이 되야 할 이유가 충분한 컴포넌트들만 리렌더링이 되어야 하지 않을까요?" 입니다.
> 
> 첨부해 드린 자료의 경우에는 이 질문 분기를 먼저 지나치게 됩니다.
> 
> Do consumers often only need parts of the state ?
> 본 context value를 사용하는 컴포넌트들이 state의 일부분만을 사용하고 있나요?
> 리렌더링이 빈번하게 일어나는 상황에서 Context API를 사용하는 것 그 자체가 나쁜 것은 아니라고 생각합니다. 문제는 일부분만을 사용처가 사용한다 에 있습니다. 일부분만을 사용한다는 것은 사용하지 않는 나머지 부분은 다른 컴포넌트에게만 필요한 state들을 이 컴포넌트도 구독한다 는 것을 의미하며, 이는 리렌더링을 할 필요가 없는 상황임에도 다른 state가 바뀌어 리렌더링하게 됨 을 의미합니다.
> 
> 빈번하게 리렌더링되는 state들이 있는데 이를 구독하는 컴포넌트 중 그 빈번하게 리렌더링되는 state를 사용하지 않는다는 것은 그럴 필요가 없음에도 불구하고 빈번하게 리렌더링이 된다는 것을 의미하며, 필요하지 않은 성능 비용 을 지불해야 한다는 것을 의미합니다. 따라서 대체로 좋은 상황이 아니라고 생각합니다. 하지만 성능 영향이 미미하다면 어느 정도는 불필요하게 리렌더링하는 방향이 코드 구조가 깔끔하다면 충분히 채용할 수 있는 방법도 될 것입니다.
> 
> 이렇게 말씀드리면 이제 자료가 이해가 가실까요?

네..! 이제 이해가 가네요 리렌더링이 필요하지 않는 컴포넌트까지 빈번하게 리렌더링이 된다면 확실히 좋지 않겠네요. 단순하게 효율만을 따지지 않고 깊게 생각해봐야겠어요

2024-12-07 04:13 UTC, merged