[adv-2.2단계] 송혜정 미션 제출합니다.
greedy-team/self-paced-react-advanced pull request #7
Opened 2024-12-24 08:31 UTC by Songhyejeong

안녕하세요 리뷰어님 🙂
오랜만에 다시 미션 진행해봤는데 어떠셨나요? 
저는 지난 미션에서 전역 상태 관리를 구현 해보기 했고 Recoil이 간단해서 빠르게 구현할 수 있었던 것 같아요! 다만 Recoil이 처음이라서 이렇게 `useSetRecoilState`, `useRecoilValue`를 잘 사용한 건지 모르겠네요..
 
이번 리뷰도 잘 부탁드리고 즐거운 연말 되세요 ~!

## 🎯 요구사항
 Recoil를 사용해서 애플리케이션 내의 Context API로부터의 마이그레이션

### Recoil을 사용하는 이유
전역 상태 관리를 쉽게 할 수 있습니다. key와 default 값을 atom으로 정의해주면, 어느 컴포넌트에서든 간단하게 접근이 가능합니다.

### Context API, Recoil trade-off
1. **Recoil**: Recoil이 Context에 비해 간단하게 상태를 관리할 수 있습니다. Recoil은 atom을 통해 컴포넌트에서 필요한 값만 구독하여 불필요한 리렌더링을 방지합니다. 

2.   **Context API** : 별도의 설치 과정이 필요하지 않습니다.  소규모 프로젝트에서 상태 변화가 적은 간편한 전역 상태를 관리하고자 할 때 적합합니다. 하지만 Context는 루트 컴포넌트의 모든 하위 컴포넌트가 컨텍스트를 구독 하므로, 불필요한 렌더링이 발생할 수 있습니다.

### 파일 구조

<img width="736" alt="Screenshot 2024-12-24 at 5 18 37 PM" src="https://github.com/user-attachments/assets/35996df9-6fc2-408c-b6c9-c441bb688c04" />

## 작동 영상
https://github.com/user-attachments/assets/e88dde1e-6464-4c8e-b919-8c78ad1b969a

2025-01-02 03:06 UTC, gogo1414 approved these changes
안녕하세요, 혜정님!
정말 오랜만에 리뷰를 하네요...!

저는 미션을 진행하면서 그 전에 했던 것들을 리마인드 해보는 시간을 가져봤는데 혜정님은 어떠셨나요??

작성해주신 `useSetRecoilState`, `useRecoilValue` 모두 잘 사용하신거 같아요!
`useSetRecoilState`의 경우 변경만 하기 위해서 사용하는 것이고 `useRecoilValue`는 읽기만 하기 위해 사용하는 것으로 알고있는데 모두 적절하게 사용된거 같아요!
조금 신기했던 점은 상태 변경을 위한 setRestaurants를 매개변수로 전달하는 점이 신기했어요! Recoil을 사용하면 `setRestaurants`를 `postRestaurant()` 내에서 자체적으로 사용 가능하지 않을까 싶어서 해당 부분은 전달이 아니라 그냥 함수를 실행하는 형태로 해도 작동하지 않을까요??

나머지 부분은 모두 잘 봤습니다!
고생하셨어요!

2025-01-02 03:06 UTC, gogo1414 commented on src/components/aside/AddRestaurantModal.jsx
>    const [description, setDescription] = useState('');
해당 부분은 모달 내에서만 사용해서 Recoil을 사용 안하시는 걸까요??

2025-01-02 05:57 UTC, Songhyejeong commented on src/components/aside/AddRestaurantModal.jsx
>    const [description, setDescription] = useState('');
모달 내에서만 사용하기도 하고, 한 글자 입력할 때마다 변하는 폼 상태를 전역으로 저장하는 것이 불필요하다고 생각해서, 컴포넌트 내에서 관리하는 것이 더 좋을 거 같다고 생각했습니다!

2025-01-02 06:05 UTC, Songhyejeong commented
안녕하세요 준수님! 리뷰 감사합니다 !
>조금 신기했던 점은 상태 변경을 위한 setRestaurants를 매개변수로 전달하는 점이 신기했어요! Recoil을 사용하면 `setRestaurants`를 `postRestaurant()` 내에서 자체적으로 사용 가능하지 않을까 싶어서 해당 부분은 전달이 아니라 그냥 함수를 실행하는 형태로 해도 작동하지 않을까요??
> 
오.. 그러게요 setRestaurants를 전달하지 않아도 될 거 같네요! 한 번 적용해보겠습니다~ 👍

2025-01-03 09:16 UTC, Indigochi1d requested changes
오랜만에 미션은 어떠셨나요?😄  2024년에 해오다가 25년에 하는 첫 리뷰네요! ContextAPI에 비해 `recoil`을 사용하는 것은 굉장히 쉬웠을거라고 생각해요. 실제로 러닝커브가 매우 작은 편이기도 하구요. 전역상태를 `atom`으로 선언하고 `hooks`를 써서 상태를 끌고 오는 것은 굉장히 편해요. `useState`의 동작방식과도 유사합니다. 

근데 이것만 쓴다면 `recoil` 이 너무 단순하겠죠? 저희 오늘 스터디에서 같이 공부했다싶이 `recoil`에서는 "그래프 구조"를 가져가는 것이 특징입니다. `selector`를 통해 많은 것을 할 수 있어요. 상태를 구독하며 파생시켜 사용할 수 있고 또 비동기처리 로직도 `useEffect`를 하지 않고도 처리할  수 있습니다. 캐싱은 덤이겠죠? 물론 캐싱관련 억까들이 존재했던 것도 기억하실거에요!
오늘 스터디 내용을 한번 복기 해보시고 `recoil` 공식문서를 본다면 많은 도움이 될 거에요. 공식문서도  읽기 쉽고 이해하기 쉽더라구요. 이번 미션도 고생하셨습니다! 다음주 금요일에  봐요 ✋🏻

2025-01-04 17:48 UTC, Songhyejeong commented on src/components/main/main/Main.jsx
> +  }, []);
넵 반영해보겠습니다!~

2025-01-06 03:33 UTC, Songhyejeong commented
@Indigochi1d 안녕하세요 범수님! 리뷰 감사합니다~!

리뷰를 반영하는 과정에서 궁금한 점이 생겨 답변 남깁니다! 🙂 

### 1. post 요청 후 get요청
selector를 사용해서 get요청하는 것은 atom이 변경될 때 selector가 실행되어 get요청을 보내는 것으로 이해를 했지만 

post요청 후 get요청 하는 방식이 아직 잘 와닿지 않습니다...

모달 폼을 제출하는 로직에서 post 요청 후에 바로 get 요청을 보내기 위해서, selector의 atom 의존성을 활용하려 했습니다.

실행 순서는  `setNewRestaurant` atom 업데이트→ `restaurantFormQuery` selector(Post요청)실행 → `setRestaurants` 업데이트(서버 동기화)& atom 업데이트→ `restaurantsQuery` 실행(get 요청) 으로 실행되게 하고자 했는데  

이런식으로 post요청 후 restaurants atom을 직접 변경 해서 **서버의 데이터와 동기화 한 후** 👀, get 요청 요청을 보내는 방법이 맞는지 궁금합니다..!  

답변 남겨주시면 감사하겠습니당🙂

2025-01-07 15:15 UTC, Indigochi1d requested changes
> 실행 순서는 setNewRestaurant atom 업데이트→ restaurantFormQuery selector(Post요청)실행 → setRestaurants 업데이트(서버 동기화)& atom 업데이트→ restaurantsQuery 실행(get 요청) 으로 실행되게 하고자 했는데
> 
> 이런식으로 post요청 후 restaurants atom을 직접 변경 해서 서버의 데이터와 동기화 한 후 👀, get 요청 요청을 보내는 방법이 맞는지 궁금합니다..!

라고 질문 주셨어요. 우선 저는 이 방법이 조금 비효율적인 방법이 될 수 있다고 생각합니다. `restuarants atom`을 직접 변경한 후` GET요청`을 통해 서버의 데이터와 동기화하는 작업은 결과적으로 상태를 두 번 참조하는 결과가 된다고 생각해요. 애플리케이션이 돌아가긴 하지만 `restaurants` 을 직접 변경한다면 `POST`한 후의 `GET`요청을 해오는 의미가 없다고 생각합니다. 이때의 `GET`요청은 서버 데이터와의 동기화의 목적을 가지는데 `POST`할때 직접 상태를 변경한다면 동기화의 목적 부분에서 괴리감이 생기기 때문입니다. 
따라서 만약 코드를 변화시켜야한다면 저는 `useRecoilRefresher_UNSTABLE` hook을 쓸 것 같습니다. 이것이 뭔지는 [링크](https://recoiljs.org/ko/docs/api-reference/core/useRecoilRefresher/)에 달아놓을게요!

그래서 혜정님의 코드를 변화시켜보면
```javascript
import { useEffect, useState } from 'react';
import styled from 'styled-components';
import { CATEGORYOPTION } from '../constants/CategoryOption';
import Modal from '../common/modal/Modal';
import { v4 as uuidv4 } from 'uuid';
import { useRecoilValue, useSetRecoilState, useRecoilRefresher_UNSTABLE } from 'recoil';
import {
  newRestaurantState,
  restaurantFormQuery,
} from '../../recoil/RestaurantFormState';
import { addModalState } from '../../recoil/ModalState';
import { restaurantsQuery } from '../../recoil/RestaurantListState';


const AddRestaurantModal = () => {
  const [category, setCategory] = useState('');
  const [name, setName] = useState('');
  const [description, setDescription] = useState('');
  const [isCompleted, setIsCompleted] = useState(false);

  const setNewRestaurant = useSetRecoilState(newRestaurantState);
  const setAddModal = useSetRecoilState(addModalState);
  const restaurantForm = useRecoilValue(restaurantFormQuery);
  const refreshRestaurants = useRecoilRefresher_UNSTABLE(restaurantsQuery);
  const newRestaurant = {
    id: uuidv4(),
    category,
    name,
    description,
  };

  const checkFormHandler = (e) => {
    e.preventDefault();
    setNewRestaurant(newRestaurant);
    setIsCompleted(true);
  };

  useEffect(() => {
    if (isCompleted && restaurantForm.ok) {
      refreshRestaurants();
      setAddModal(false);
    }
  }, [isCompleted]);

  return (
    <Modal title="새로운 음식점" onClose={() => setAddModal(false)}>
      { ..... }
    </Modal>
  );
};

export default AddRestaurantModal;
```

이렇게 할 것 같아요. useEffect 에서 POST요청 값이 ok가 됨을 확인했을 때 refresh를 걸면 자연스럽게 GET을 트리거 할 수 있다고 생각합니다! 공식문서에도 이러한 방향으로 사용하라고 나와있기도 하구요. 

또는 로직 자체에서 `POST`한 selector를 사용하고 그 이후에 `GET` 요청을 보내주면서 해결할 수도 있습니다! 

➕ 추가) 저는 `restaurantsQuery`를 이렇게 바꿨습니다.
```javascript
import { atom, selector } from 'recoil';
import { getRestaurant } from '../api/restaurant';

const restaurantsState = atom({
  key: 'restaurants',
  default: [],
});

const restaurantsQuery = selector({
  key: 'restaurantsQuery',
  get: async ({ get }) => {
    const currentRestaurants = get(restaurantsState);
    try {
      const updatedRestaurants = await getRestaurant();
      return updatedRestaurants || currentRestaurants;
    } catch (error) {
      console.error('Error fetching restaurants:', error);
      return currentRestaurants;
    }
  },
});

export { restaurantsState, restaurantsQuery };
```

2025-01-08 12:36 UTC, Songhyejeong commented
리뷰 반영해서  `useRecoilRefresher_UNSTABLE`도 적용하고 오류 처리 방식도 범수님이 보여주신 코드처럼 바꿔서 리팩터링 진행했습니다 !

> 라고 질문 주셨어요. 우선 저는 이 방법이 조금 비효율적인 방법이 될 수 있다고 생각합니다. `restuarants atom`을 직접 변경한 후` GET요청`을 통해 서버의 데이터와 동기화하는 작업은 결과적으로 상태를 두 번 참조하는 결과가 된다고 생각해요. 애플리케이션이 돌아가긴 하지만 `restaurants` 을 직접 변경한다면 `POST`한 후의 `GET`요청을 해오는 의미가 없다고 생각합니다. 이때의 `GET`요청은 서버 데이터와의 동기화의 목적을 가지는데 `POST`할때 직접 상태를 변경한다면 동기화의 목적 부분에서 괴리감이 생기기 때문입니다. 따라서 만약 코드를 변화시켜야한다면 저는 `useRecoilRefresher_UNSTABLE` hook을 쓸 것 같습니다. 이것이 뭔지는 [링크](https://recoiljs.org/ko/docs/api-reference/core/useRecoilRefresher/)에 달아놓을게요!
> 
> 그래서 혜정님의 코드를 변화시켜보면
> 
> ```js
> import { useEffect, useState } from 'react';
> import styled from 'styled-components';
> import { CATEGORYOPTION } from '../constants/CategoryOption';
> import Modal from '../common/modal/Modal';
> import { v4 as uuidv4 } from 'uuid';
> import { useRecoilValue, useSetRecoilState, useRecoilRefresher_UNSTABLE } from 'recoil';
> import {
>   newRestaurantState,
>   restaurantFormQuery,
> } from '../../recoil/RestaurantFormState';
> import { addModalState } from '../../recoil/ModalState';
> import { restaurantsQuery } from '../../recoil/RestaurantListState';
> 
> 
> const AddRestaurantModal = () => {
>   const [category, setCategory] = useState('');
>   const [name, setName] = useState('');
>   const [description, setDescription] = useState('');
>   const [isCompleted, setIsCompleted] = useState(false);
> 
>   const setNewRestaurant = useSetRecoilState(newRestaurantState);
>   const setAddModal = useSetRecoilState(addModalState);
>   const restaurantForm = useRecoilValue(restaurantFormQuery);
>   const refreshRestaurants = useRecoilRefresher_UNSTABLE(restaurantsQuery);
>   const newRestaurant = {
>     id: uuidv4(),
>     category,
>     name,
>     description,
>   };
> 
>   const checkFormHandler = (e) => {
>     e.preventDefault();
>     setNewRestaurant(newRestaurant);
>     setIsCompleted(true);
>   };
> 
>   useEffect(() => {
>     if (isCompleted && restaurantForm.ok) {
>       refreshRestaurants();
>       setAddModal(false);
>     }
>   }, [isCompleted]);
> 
>   return (
>     <Modal title="새로운 음식점" onClose={() => setAddModal(false)}>
>       { ..... }
>     </Modal>
>   );
> };
> 
> export default AddRestaurantModal;
> ```
> 
> 이렇게 할 것 같아요. useEffect 에서 POST요청 값이 ok가 됨을 확인했을 때 refresh를 걸면 자연스럽게 GET을 트리거 할 수 있다고 생각합니다! 공식문서에도 이러한 방향으로 사용하라고 나와있기도 하구요.
> 
> 또는 로직 자체에서 `POST`한 selector를 사용하고 그 이후에 `GET` 요청을 보내주면서 해결할 수도 있습니다!

오..! 뭔가 동기화 하면서도 다른 좋은 방법이 있을거라 생각했는데 이런게 있었네요. 직접 코드까지 수정해주셔서 쉽게 이해갑니다..! 감사합니다! 👍 

> ➕ 추가) 저는 `restaurantsQuery`를 이렇게 바꿨습니다.
> 
> ```js
> import { atom, selector } from 'recoil';
> import { getRestaurant } from '../api/restaurant';
> 
> const restaurantsState = atom({
>   key: 'restaurants',
>   default: [],
> });
> 
> const restaurantsQuery = selector({
>   key: 'restaurantsQuery',
>   get: async ({ get }) => {
>     const currentRestaurants = get(restaurantsState);
>     try {
>       const updatedRestaurants = await getRestaurant();
>       return updatedRestaurants || currentRestaurants;
>     } catch (error) {
>       console.error('Error fetching restaurants:', error);
>       return currentRestaurants;
>     }
>   },
> });
> 
> export { restaurantsState, restaurantsQuery };
> ```

오류가 났을 때 currentRestaurants를 반환하면 currentRestaurants를 UI로 보여줘서 사용자 경험 측면에서 좋겠네요!

2025-01-08 13:24 UTC, Indigochi1d commented
@Songhyejeong 수고하셨어요👏🏻👏🏻👏🏻

2025-01-08 13:29 UTC, merged

2025-01-10 02:12 UTC, Indigochi1d reviewed
👍🏻

2025-01-10 15:22 UTC, Indigochi1d reviewed
💯