[adv-2.2단계] 김준수 미션 제출합니다.
greedy-team/self-paced-react-advanced pull request #8
Opened 2024-12-31 09:27 UTC by gogo1414

안녕하세요! 리뷰어님😊
진짜 오랜만에 미션을 진행해서 다 까먹어서 힘들었네요...
상태 관리를 마이그레이션 해보면서 느낀게 Context API 보다 확실히 Recoil 사용이 더 편리한거 같아요! 이전에 복잡하게 사용했던 토글도 이제 사라지니 코드 관리가 더 용이해졌어요..!👍

이번 리뷰 잘 부탁드리고 새해 복 많이 받으세요!

## 요구사항
Recoil을 사용해서 애플리케이션 내의 Contexet API로부터의 마이그레이션 진행하기

### Recoil을 왜 사용할까?
상태 관리를 보다 용이하게 하기 위해서 사용하는게 아닐까 싶어요!
자세하게 적어보자면 하나의 상태를 저 깊은 심연 계층까지 전달을 계속해야하는데, 일부 수정으로 인해 이 부분의 수정이 필요하면 매우 복잡해져서 그러지 않을까요..?

### Context API VS Recoil 비교
확실하게 느낀건 Context API 보다 작성하는게 더 쉬웠어요! 뭔가 복잡한 내용이 있다기 보다 정말 상태를 적고 그 상태를 사용하고 변경하는 것에 초점이 맞춰줘서 그런지 Context API 보다 생각해야할 내용이 적었던 것 같네요!

Trade OFF의 경우에는 기존 토글 모달 함수에서 다양한 상태가 엉켜있었는데 이번 Recoil을 적용하면서 토글 모달에 복잡하게 의존하던 함수를 제거할 수 있었어요! 해당 부분에서 너무 좋았네요

## 데이터 구조
<img width="790" alt="스크린샷 2024-12-31 오후 6 26 54" src="https://github.com/user-attachments/assets/d92d206d-7024-4ee2-812b-feccc6517858" />

## 동작 사진
<img width="1840" alt="스크린샷 2024-12-31 오후 6 23 55" src="https://github.com/user-attachments/assets/690bbc51-3e1d-4521-8c10-9b50242a10c3" />
<img width="1840" alt="스크린샷 2024-12-31 오후 6 23 59" src="https://github.com/user-attachments/assets/bb2ef9ee-b5a4-4036-842b-08d3275f0cbc" />
<img width="1840" alt="스크린샷 2024-12-31 오후 6 24 03" src="https://github.com/user-attachments/assets/0b44bed7-6883-4fd6-9e0e-3b9d27ced4a4" />
9" />
<img width="1840" alt="스크린샷 2024-12-31 오후 6 24 06" src="https://github.com/user-attachments/assets/04181342-5f1a-4d05-ade2-989286b3c71c" />
<img width="1840" alt="스크린샷 2024-12-31 오후 6 24 16" src="https://github.com/user-attachments/assets/bb83fdfc-6093-4553-a76f-b29950087d8d" />

2025-01-02 05:45 UTC, Songhyejeong reviewed
안녕하세요 준수님! 
저도 이번 미션하면서 Context보다 Recoil 적용한 코드 훨씬 간결하고 편리하다고 느꼈는데 비슷하게 느끼신 거 같아요! 데이터 구조도 깔끔하네요  
준수님이 말씀하신 것처럼 모달 같이 여러 컴포넌트에 상태가 엉켜있을 경우에 Recoil로 상태를 관리하면 이점이 많은 거 같아요!
몇가지 궁금한 점은 코드에 리뷰 달아놨습니다 ! 

오랜만에 미션 하시느라 수고하셨습니다 ~

2025-01-02 05:45 UTC, Songhyejeong commented on src/recoil/CategoryState.jsx
> +import { atom } from 'recoil';
상태별로 나누니까 코드가 간결해지면서 알아보기 쉬워졌네요! 👍

2025-01-02 05:45 UTC, Songhyejeong commented on src/components/Aside/AddRestaurantModal.jsx
> +        });
이번 미션과는 조금 다른 주제이기는 한데 폼을 비제어 컴포넌트로 구현하신거 같아요..! 
`const formJson = Object.fromEntries(formData.entries());
Comment
`
이 줄의 작동 방식이 궁금하네요 값들을 객체로 만드는 건가요? 
그리고 제어 컴포넌트가 대신 비제어 컴포넌트 방식으로 구현하신 이유가 궁금합니당

2025-01-02 05:45 UTC, Songhyejeong commented on src/hooks/useRestaurants.js
> +    const [ restaurantList, setRestaurantList ] = useRecoilState(restaurantListState);
저도 restaurants와 restaurantList를 번갈아 가면서 사용했는데 의미하는바가 같으니 하나로 통일하면 더 좋을거 같아요!

2025-01-02 05:45 UTC, Songhyejeong commented on src/recoil/ModalState.jsx
> +export const modalState = atom({
오.. 이렇게 관리하면 모달이 많아질 경우에, 관리할 상태를 여러개 만들지 않아도 되어 좋은 거 같아요..! 👍

2025-01-02 13:03 UTC, gogo1414 commented on src/recoil/ModalState.jsx
> +export const modalState = atom({
기존에 작성했던 것들을 최대한 하려고 보니까 이렇게 되었네요..!

2025-01-02 13:07 UTC, gogo1414 commented on src/hooks/useRestaurants.js
> +    const [ restaurantList, setRestaurantList ] = useRecoilState(restaurantListState);
저도 비슷한 이름들이 많아져서 조금 명확하게 하려고 바꿨어요!

2025-01-02 13:18 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +        });
저도 자세하게는 모르지만 설명을 드려보자며

`const formData = new FormData(event.target);` 해당 줄을 통해 form 데이터를 가져오고
`const formJson = Object.fromEntries(formData.entries());` 데이터 중 제가 가져오고자 하는 데이터를 [ key, value ] 형태의 객체로 가져오는 걸로 알고 있어요!

비제어 컴포넌트에 대해서는 [클릭](https://github.com/cho-log/self-paced-react/pull/32#discussion_r1835372370)에서도 들었어요! 제가 제어 컴포넌트와 비제어 컴포넌트에 대해 정확하게 알지 못해서 비제어 컴포넌트로 구현했었던 것인데 동작 과정에서 큰 문제가 보이지 않아서 아직까지 유지하고 있네요😊

2025-01-04 16:52 UTC, wzrabbit requested changes
@gogo1414 👋🏻 리뷰가 늦어져서 죄송합니다. 오랜만에 리뷰하는 것도 있고, 최근 다른 개발해야 할 일들이 엄청나게 많이 늘다보니 그만큼 리뷰를 늦게 하게 되었어요.

## 1️⃣ 리뷰
### Recoil ⏫ 
제가 항상 느끼는 거지만 새로운 라이브러리를 막힘없이 잘 소화하시는 것 같아요. 사용법을 잘 숙지하시고 적용하고 계신 것 같습니다. `recoil` 디렉토리로 별도로 recoil 상태들을 두고, `<RecoilRoot>` 로 최상단에 이러한 상태들을 사용할 수 있도록 해 주시고, 그리고 상황에 따라 `useRecoilState` / `useRecoilValue` / `useRecoilSetValue` 를 잘 활용해 주신 것도 좋았어요. 특히 `useRcoilSetValue` 는 단독으로 사용할 경우 해당 상태를 구독하지 않는 효과를 얻기 때문에 `useRecoilState`를 사용했을 때와 비교했을 때 불필요한 리렌더링의 대상이 되지 않을 수도 있어요.

Recoil은 Context API보다는 보일러플레이트가 확실히 작은 것도 있고 각 상태마다 `<Root>`를 매번 적어주어야 하는 일은 적다 보니 한결 가벼워진 느낌은 드실 거에요. 대신 멋지고 체계적인 상태를 설계하려고 하면 난이도가 꽤 상승하는 라이브러리이기도 합니다. 그만큼 잘 써야 하는 것 같아요. 저도 너무 어렵습니다.

### 커스텀 훅 👜 
미션에서 별도의 요구사항이 없었음에도 스스로 커스텀 훅을 도입하신 점이 인상깊었어요. 이전 미션에서 사용해 주신 것 같은데 이전 미션에서는 커스텀 훅에 대한 이야기가 별도로 없었어서 제가 이야기를 꺼내보았어요. 다만 기능적으로 예기치 못한 일이 (제 생각에는) 하나 발생하고 있는데 이는 코멘트로 적어드렸습니다.

앞으로도 커스텀 훅을 사용하시면서 아래의 고민거리들도 고민해 보시면 좋을 것 같아요.

- 커스텀 훅은 왜 쓸까? 커스텀 훅을 쓰는 나만의 기준은?
- 커스텀 훅을 잘 활용한다면 어떤 장점을 기대할 수 있을까?

커스텀 훅은 저도 고민을 자주 하고 밥먹듯이 쓰고 있는지라 궁금하실 경우 저한테 궁금한 점들을 질문해 주셔도 좋습니다 👍🏻 

### 상태 관리 라이브러리를 사용해도 props, state는 여전히 중요하다 ✅ 
React의 state는 상태 관리 라이브러리들의 전역 상태들을 다루는 기능의 **하위 호환이 아니라는 사실** 을 말씀드리고 싶습니다. 이들은 상호보완적이에요. 그러니 상황에 따라 상태를 전역으로 관리할 지를 고민해 보실 것을 추천드려요.

- 깊이가 깊은 계층의 상태를 사용해야 하거나, 사용처가 여러 계층에 걸쳐 너무 많아 props drilling으로 관리하기 힘든 경우에서 전역 상태 관리는 탁월한 선택이 될 수 있을 겁니다.
- 데이터 흐름이 이미 깔끔하거나, 상태가 한 곳에서만 쓰이거나, 간단한 구조라면 전역 상태들을 다루려는 시도는 오히려 구조를 복잡하게 만들며 데이터의 원천을 예측하기 힘든 코드가 될 수 있습니다.

참고(리뷰 중 코멘트): https://github.com/greedy-team/self-paced-react-advanced/pull/6#pullrequestreview-2471301895

## 2️⃣ 추가 미션
스터디를 통해 메인테이너님이 Recoil에 대해 추가 설명해 주신 것으로 알고 있어요. **그래프 구조** 처럼 상태가 뻗어나가는 형태로 상태들을 관리하는 특징도 설명해 주셨을 것 같네요. 이러한 재밌는 특징들에도 불구하고 "Context API보다 조금 쓰기 쉬운 state" 라고 생각하고 넘어간다면 너무 아쉽겠죠.

![image](https://github.com/user-attachments/assets/8b9a18aa-6c17-44b4-ae78-6d14ec00c9d1)

### 미션

![image](https://github.com/user-attachments/assets/2d581089-fe76-4d8c-91eb-35b49882c631)


이번 미션에서는, **selector**라는 것을 사용해 atom에 비동기 요청을 통해 받아온 레스토랑 정보를 파생시켜 봅시다. 보통은 atom으로부터 selector를 파생시키는 경우가 많지만 반대도 가능하며 비동기 로직을 쓸 경우 특히 이러한 케이스가 많습니다.

요구 사항:
- 커스텀 훅 등 외부에서 레스토랑 정보를 받아와 `restaurantListState` atom에 직접 갱신하지 않고, selector를 사용해 `restaurantListState` atom이 초깃값으로 외부에서 받아온 레스토랑 정보를 지니도록 개선해 주세요.

힌트:
1. atom의 `default` 프로퍼티의 값을 selector로 두면 atom이 selector로부터 반환받은 값을 지니도록 할 수 있어요.
2. atom은 원칙적으로 바로 사용할 수 있는 값을 지녀야 해요. 비동기 값을 지니는 등으로 당장 그 값을 활용할 수 없는 상황이 되어서는 안 됩니다. 이 경우 에러가 발생할 수 있습니다. React의 Suspense, 또는 Recoil의 Loadable을 활용해 이에 대응할 수 있습니다 (개인적으로 처음 하시는 입장에서는 Suspense를 추천드립니다)

저는 여기까지 하겠습니다. 수고 많으셨어요 👍🏻

2025-01-04 16:52 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
> +        });
비제어 컴포넌트는 잘못된 방식은 아닙니다. 둘의 차이점은 "React에 의해 그 폼들의 값이 관리되는가/그렇지 않은가" 가 주요 토픽입니다.

복잡한 폼을 다루는 등 특정한 상황이 아니라면 비제어 컴포넌트/제어 컴포넌트 모두 충분히 활용할 수 있는 방식입니다. React를 떠나 폼 자체에 아직 익숙하지 않으신 경우 어느 방식이든 동작하도록 먼저 설계해 주셔도 충분합니다. 그러니 너무 걱정하지는 마세요.

수요 자체를 말씀드리자면 그래도 특별한 상황이 아니면 제어 컴포넌트가 대체로 선호되는 추세입니다. React에 의해 상태 및 값이 관리되는 이점이 있기 때문이에요. 다만 여기에서 제어 컴포넌트를 사용할 경우에 큰 단점이 예상되는 경우 비제어 컴포넌트의 형태로 관리하는 방식을 채용하기도 합니다.
- 사용자가 값을 입력할 때마다 검증할 필요가 없는 경우
- 빈번한 리렌더링이 큰 오버헤드로 작용하는 경우
...

2025-01-04 16:52 UTC, wzrabbit commented on src/recoil/ClickedRestaurantState.jsx
> +import { atom } from 'recoil';
## 🎤 인터뷰
1. `atom` 은 무엇인가요?
2. `selector` 는 무엇인가요?

필요하실 경우 [Recoil 공식 문서](https://recoiljs.org/ko/docs/basic-tutorial/atoms) 를 확인해 주셔도 좋습니다!

2025-01-08 07:24 UTC, gogo1414 commented on src/components/Main/RestaurantList.jsx
> +    const restaurants = useRecoilValue(restaurantListState);
커스텀 훅에서 `restaurantList`를 반환하고 있었네요..! 저도 미션을 보면서 지금 눈치챘습니다..🥲

2025-01-08 07:28 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +import {useRestaurants} from "../../hooks/useRestaurants.js";
흠 해당 부분에 대해서는 자세히는 모르지만 커스텀 훅은 자바 스크립트로 동작해서 확장자를 `.js`로 두었고, `.jsx`의 경우 리액트의 라이브러리라고 생각하여 `.jsx`로 두었어요!

2025-01-08 07:30 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +    const setIsModalOpen = useSetRecoilState(modalState);
말씀해주신대로 저도 **원하는 것만 사용**할 수 있는 점에서 `Recoil`의 사용이 매우 효율적이라고 생각했어요!
전에는 쓰지 않았던 것들도 같이 선언하느라 불필요한 코드들도 작성해야했지만, `Recoil`은 그런 부분이 없어서 매우 좋았네요😊

2025-01-08 07:33 UTC, gogo1414 commented on src/components/Aside/AddRestaurantModal.jsx
> +    const { addRestaurant } = useRestaurants();
해당 부분은 라이브러리를 적용하면서 기존 의도와는 다른 방향으로 진행된 것 같아요!

제가 원했던 건 실제로 레스토랑을 추가했을 때만 다시 레스토랑 정보를 가져오도록 의도 했었는데 지금 보니 문제가 생겼네요..!

2025-01-08 08:27 UTC, gogo1414 commented on src/recoil/ClickedRestaurantState.jsx
> +import { atom } from 'recoil';
> 1. atom 은 무엇인가요?

=>  저는 `atom`을 상태 관리를 위한 하나의 틀이자 상태 저장소라고 생각합니다. 

> 2. `selector` 는 무엇인가요?

=> `atom`으로 정의한 상태 값에 대한 변경을 위해 사용하는 것을 의미한다고 생각합니다.

2025-01-08 11:20 UTC, wzrabbit commented on src/components/Aside/AddRestaurantModal.jsx
> +import {useRestaurants} from "../../hooks/useRestaurants.js";
- `.js` 와 비교했을 때 확장자가 `.jsx` 라면 어떤 추가 기능을 사용할 수 있을까요?
- React에서 JSX 문법을 사용하고 있는 컴포넌트의 확장자인 `.jsx`를 마음대로 `.js`로 바꾸면 무슨 일이 일어나며, 왜 그 "무슨 일" 일이 일어나게 될까요?

이 부분을 고민해 보시면 좋을 것 같아요

2025-01-08 15:02 UTC, wzrabbit approved these changes
👋🏻 반영 및 추가 미션까지 수행하시느라 고생 많으셨습니다!

불필요한 비동기 요청이 일어나지 않도록 커스텀 훅을 분리하신 것 확인했고, Selector를 이용해 Atom이 초깃값으로 비동기 상태를 받아올 수 있도록 구현하는 부분도 잘 수행하셨습니다. Selector와 Atom의 관계를 잘 맺어주셨어요.

 다만 이 Recoil 상태를 활용하는 컴포넌트에서는 문제가 발생할 수도 있는 것이 예상됩니다. 추가 미션 소개 시 Suspense를 설명했을 거에요. 이번 피드백에서는 간략하게 Suspense가 여기에서 왜 필요한 지 소개하며 마치겠습니다.

1. Recoil의 Atom에 대응하는 초기 상태값은 **처음부터 준비되어 있지 않습니다.** Selector에서 비동기 요청을 한 후, 응답을 받아야 그제서야 초기 상태값이 사용 가능한 상태가 됩니다.
2. 이 상태값을 사용하는 컴포넌트에서, 초기 상태값이 준비되기 **전에 먼저 렌더링을 하는 경우가 ** 생길 수 있습니다. 이 경우에는 문제가 생길 수 있겠죠?
3. 그렇기 때문에 이러한 비동기 로직들이 끝날 때까지 **컴포넌트의 렌더링을 잠시 미뤄야 하는 상황** 이 있을 수 있습니다. 그럴 때 사용할 수 있는 방법 중 하나가 바로 **Suspense를 사용하는 것** 입니다.
4. **Suspense**는 렌더링을 미뤄야 하는 컴포넌트의 상위에 사용해 주시면 됩니다.

아래는 Suspense를 적용한 예시입니다. Suspense는 React에서 렌더링과 비동기를 다룰 때 자주 등장하는 개념이니 나중에라도 꼭 숙지해 두실 것을 권해 드립니다. Suspense를 올바르게 적용하면 아래의 경고도 사라질 거에요!

![image](https://github.com/user-attachments/assets/808be4b6-043b-4bbb-9e85-9a54b96bd6db)


```jsx
import "./App.css";
import Header from "./components/Header/Header.jsx";
import CategoryFilter from "./components/Main/CategoryFilter.jsx";
import RestaurantDetailModal from "./components/Aside/RestaurantDetailModal.jsx";
import AddRestaurantModal from "./components/Aside/AddRestaurantModal.jsx";
import RestaurantList from "./components/Main/RestaurantList.jsx";
import { useRecoilValue } from "recoil";
import { modalState } from "./recoil/ModalState.jsx";
import { Suspense } from "react"; // Suspense를 import하고

function App() {
  const { detail, add } = useRecoilValue(modalState);

  return (
    <>
      <Header />
      <main>
        <CategoryFilter />
        <Suspense> {/* 비동기 요청이 수행되는 로직을 지닌 컴포넌트를 감싸 사용하시면 됩니다 */}
          <RestaurantList />
        </Suspense>
      </main>
      <aside>
        {detail && <RestaurantDetailModal />}
        {add && <AddRestaurantModal />}
      </aside>
    </>
  );
}

export default App;
```

생소한 기술을 접하시고 추가 미션까지 수행하느라 고생 많이 하셨습니다!

2025-01-08 15:05 UTC, merged

2025-01-10 06:13 UTC, gogo1414 commented on src/hooks/getRestaurants.js
> +export const getRestaurants = () => {
아!! 그래서 공식 문서에도 `use-` 네이밍을 많이 보는것 같아요!
먼가 비슷한 내용들이 겹치게 되면 네이밍을 어떻게 처리해야할 지 고민이 생기다 보니 get을 그냥 써버렸네요..🥲

ESLint는 좋은 도구네요 개발자의 입장에서 세세한 부분을 찾아내기 어려운데 대신 해준다는 부분에서 좋네요!

2025-01-10 06:14 UTC, gogo1414 commented on src/components/Main/RestaurantList.jsx
> +        ? restaurantList : restaurantList.filter((restaurant) => restaurant.category === category);
맞아요 비슷한 변수들이 지속적으로 생겨나다 보니 통일과 분리를 명확하게 할 네이밍이 존재하는게 좋을거 같네요...